// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface ClickSolutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.ClickSolution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .captchasonic.v1.ClickGroup groups = 1;</code>
   */
  java.util.List<com.captchasonic.v1.ClickGroup> 
      getGroupsList();
  /**
   * <code>repeated .captchasonic.v1.ClickGroup groups = 1;</code>
   */
  com.captchasonic.v1.ClickGroup getGroups(int index);
  /**
   * <code>repeated .captchasonic.v1.ClickGroup groups = 1;</code>
   */
  int getGroupsCount();
  /**
   * <code>repeated .captchasonic.v1.ClickGroup groups = 1;</code>
   */
  java.util.List<? extends com.captchasonic.v1.ClickGroupOrBuilder> 
      getGroupsOrBuilderList();
  /**
   * <code>repeated .captchasonic.v1.ClickGroup groups = 1;</code>
   */
  com.captchasonic.v1.ClickGroupOrBuilder getGroupsOrBuilder(
      int index);
}
