// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface ClickGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.ClickGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  java.util.List<com.captchasonic.v1.ClickCoord> 
      getCoordsList();
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  com.captchasonic.v1.ClickCoord getCoords(int index);
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  int getCoordsCount();
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  java.util.List<? extends com.captchasonic.v1.ClickCoordOrBuilder> 
      getCoordsOrBuilderList();
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  com.captchasonic.v1.ClickCoordOrBuilder getCoordsOrBuilder(
      int index);
}
