// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

/**
 * Protobuf type {@code captchasonic.v1.ClickGroup}
 */
@com.google.protobuf.Generated
public final class ClickGroup extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:captchasonic.v1.ClickGroup)
    ClickGroupOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "ClickGroup");
  }
  // Use ClickGroup.newBuilder() to construct.
  private ClickGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ClickGroup() {
    coords_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_ClickGroup_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_ClickGroup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_ClickGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.captchasonic.v1.ClickGroup.class, com.captchasonic.v1.ClickGroup.Builder.class);
  }

  public static final int COORDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.captchasonic.v1.ClickCoord> coords_;
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.captchasonic.v1.ClickCoord> getCoordsList() {
    return coords_;
  }
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.captchasonic.v1.ClickCoordOrBuilder> 
      getCoordsOrBuilderList() {
    return coords_;
  }
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  @java.lang.Override
  public int getCoordsCount() {
    return coords_.size();
  }
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.ClickCoord getCoords(int index) {
    return coords_.get(index);
  }
  /**
   * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.ClickCoordOrBuilder getCoordsOrBuilder(
      int index) {
    return coords_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < coords_.size(); i++) {
      output.writeMessage(1, coords_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = coords_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(coords_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.captchasonic.v1.ClickGroup)) {
      return super.equals(obj);
    }
    com.captchasonic.v1.ClickGroup other = (com.captchasonic.v1.ClickGroup) obj;

    if (!getCoordsList()
        .equals(other.getCoordsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoordsCount() > 0) {
      hash = (37 * hash) + COORDS_FIELD_NUMBER;
      hash = (53 * hash) + getCoordsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.captchasonic.v1.ClickGroup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.captchasonic.v1.ClickGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.captchasonic.v1.ClickGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.ClickGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.captchasonic.v1.ClickGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code captchasonic.v1.ClickGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:captchasonic.v1.ClickGroup)
      com.captchasonic.v1.ClickGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_ClickGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_ClickGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.captchasonic.v1.ClickGroup.class, com.captchasonic.v1.ClickGroup.Builder.class);
    }

    // Construct using com.captchasonic.v1.ClickGroup.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (coordsBuilder_ == null) {
        coords_ = java.util.Collections.emptyList();
      } else {
        coords_ = null;
        coordsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_ClickGroup_descriptor;
    }

    @java.lang.Override
    public com.captchasonic.v1.ClickGroup getDefaultInstanceForType() {
      return com.captchasonic.v1.ClickGroup.getDefaultInstance();
    }

    @java.lang.Override
    public com.captchasonic.v1.ClickGroup build() {
      com.captchasonic.v1.ClickGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.captchasonic.v1.ClickGroup buildPartial() {
      com.captchasonic.v1.ClickGroup result = new com.captchasonic.v1.ClickGroup(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.captchasonic.v1.ClickGroup result) {
      if (coordsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          coords_ = java.util.Collections.unmodifiableList(coords_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.coords_ = coords_;
      } else {
        result.coords_ = coordsBuilder_.build();
      }
    }

    private void buildPartial0(com.captchasonic.v1.ClickGroup result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.captchasonic.v1.ClickGroup) {
        return mergeFrom((com.captchasonic.v1.ClickGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.captchasonic.v1.ClickGroup other) {
      if (other == com.captchasonic.v1.ClickGroup.getDefaultInstance()) return this;
      if (coordsBuilder_ == null) {
        if (!other.coords_.isEmpty()) {
          if (coords_.isEmpty()) {
            coords_ = other.coords_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoordsIsMutable();
            coords_.addAll(other.coords_);
          }
          onChanged();
        }
      } else {
        if (!other.coords_.isEmpty()) {
          if (coordsBuilder_.isEmpty()) {
            coordsBuilder_.dispose();
            coordsBuilder_ = null;
            coords_ = other.coords_;
            bitField0_ = (bitField0_ & ~0x00000001);
            coordsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCoordsFieldBuilder() : null;
          } else {
            coordsBuilder_.addAllMessages(other.coords_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.captchasonic.v1.ClickCoord m =
                  input.readMessage(
                      com.captchasonic.v1.ClickCoord.parser(),
                      extensionRegistry);
              if (coordsBuilder_ == null) {
                ensureCoordsIsMutable();
                coords_.add(m);
              } else {
                coordsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.captchasonic.v1.ClickCoord> coords_ =
      java.util.Collections.emptyList();
    private void ensureCoordsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        coords_ = new java.util.ArrayList<com.captchasonic.v1.ClickCoord>(coords_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.captchasonic.v1.ClickCoord, com.captchasonic.v1.ClickCoord.Builder, com.captchasonic.v1.ClickCoordOrBuilder> coordsBuilder_;

    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public java.util.List<com.captchasonic.v1.ClickCoord> getCoordsList() {
      if (coordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(coords_);
      } else {
        return coordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public int getCoordsCount() {
      if (coordsBuilder_ == null) {
        return coords_.size();
      } else {
        return coordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public com.captchasonic.v1.ClickCoord getCoords(int index) {
      if (coordsBuilder_ == null) {
        return coords_.get(index);
      } else {
        return coordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder setCoords(
        int index, com.captchasonic.v1.ClickCoord value) {
      if (coordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordsIsMutable();
        coords_.set(index, value);
        onChanged();
      } else {
        coordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder setCoords(
        int index, com.captchasonic.v1.ClickCoord.Builder builderForValue) {
      if (coordsBuilder_ == null) {
        ensureCoordsIsMutable();
        coords_.set(index, builderForValue.build());
        onChanged();
      } else {
        coordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder addCoords(com.captchasonic.v1.ClickCoord value) {
      if (coordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordsIsMutable();
        coords_.add(value);
        onChanged();
      } else {
        coordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder addCoords(
        int index, com.captchasonic.v1.ClickCoord value) {
      if (coordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoordsIsMutable();
        coords_.add(index, value);
        onChanged();
      } else {
        coordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder addCoords(
        com.captchasonic.v1.ClickCoord.Builder builderForValue) {
      if (coordsBuilder_ == null) {
        ensureCoordsIsMutable();
        coords_.add(builderForValue.build());
        onChanged();
      } else {
        coordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder addCoords(
        int index, com.captchasonic.v1.ClickCoord.Builder builderForValue) {
      if (coordsBuilder_ == null) {
        ensureCoordsIsMutable();
        coords_.add(index, builderForValue.build());
        onChanged();
      } else {
        coordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder addAllCoords(
        java.lang.Iterable<? extends com.captchasonic.v1.ClickCoord> values) {
      if (coordsBuilder_ == null) {
        ensureCoordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coords_);
        onChanged();
      } else {
        coordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder clearCoords() {
      if (coordsBuilder_ == null) {
        coords_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        coordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public Builder removeCoords(int index) {
      if (coordsBuilder_ == null) {
        ensureCoordsIsMutable();
        coords_.remove(index);
        onChanged();
      } else {
        coordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public com.captchasonic.v1.ClickCoord.Builder getCoordsBuilder(
        int index) {
      return internalGetCoordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public com.captchasonic.v1.ClickCoordOrBuilder getCoordsOrBuilder(
        int index) {
      if (coordsBuilder_ == null) {
        return coords_.get(index);  } else {
        return coordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public java.util.List<? extends com.captchasonic.v1.ClickCoordOrBuilder> 
         getCoordsOrBuilderList() {
      if (coordsBuilder_ != null) {
        return coordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(coords_);
      }
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public com.captchasonic.v1.ClickCoord.Builder addCoordsBuilder() {
      return internalGetCoordsFieldBuilder().addBuilder(
          com.captchasonic.v1.ClickCoord.getDefaultInstance());
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public com.captchasonic.v1.ClickCoord.Builder addCoordsBuilder(
        int index) {
      return internalGetCoordsFieldBuilder().addBuilder(
          index, com.captchasonic.v1.ClickCoord.getDefaultInstance());
    }
    /**
     * <code>repeated .captchasonic.v1.ClickCoord coords = 1;</code>
     */
    public java.util.List<com.captchasonic.v1.ClickCoord.Builder> 
         getCoordsBuilderList() {
      return internalGetCoordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.captchasonic.v1.ClickCoord, com.captchasonic.v1.ClickCoord.Builder, com.captchasonic.v1.ClickCoordOrBuilder> 
        internalGetCoordsFieldBuilder() {
      if (coordsBuilder_ == null) {
        coordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.captchasonic.v1.ClickCoord, com.captchasonic.v1.ClickCoord.Builder, com.captchasonic.v1.ClickCoordOrBuilder>(
                coords_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        coords_ = null;
      }
      return coordsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:captchasonic.v1.ClickGroup)
  }

  // @@protoc_insertion_point(class_scope:captchasonic.v1.ClickGroup)
  private static final com.captchasonic.v1.ClickGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.captchasonic.v1.ClickGroup();
  }

  public static com.captchasonic.v1.ClickGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClickGroup>
      PARSER = new com.google.protobuf.AbstractParser<ClickGroup>() {
    @java.lang.Override
    public ClickGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClickGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClickGroup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.captchasonic.v1.ClickGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

