// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface CreateTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.CreateTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 errorId = 1;</code>
   * @return The errorId.
   */
  int getErrorId();

  /**
   * <code>string errorDescription = 2;</code>
   * @return The errorDescription.
   */
  java.lang.String getErrorDescription();
  /**
   * <code>string errorDescription = 2;</code>
   * @return The bytes for errorDescription.
   */
  com.google.protobuf.ByteString
      getErrorDescriptionBytes();

  /**
   * <code>string taskId = 3;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string taskId = 3;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  int getSolutionCount();
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  boolean containsSolution(
      java.lang.String key);
  /**
   * Use {@link #getSolutionMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getSolution();
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getSolutionMap();
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  /* nullable */
java.lang.String getSolutionOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  java.lang.String getSolutionOrThrow(
      java.lang.String key);

  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
   * @return Whether the typedSolution field is set.
   */
  boolean hasTypedSolution();
  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
   * @return The typedSolution.
   */
  com.captchasonic.v1.SolutionPayload getTypedSolution();
  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
   */
  com.captchasonic.v1.SolutionPayloadOrBuilder getTypedSolutionOrBuilder();

  /**
   * <pre>
   * ── REST parity fields ──────────────────────────────────────────────
   * Extension expects same response shape as HTTP endpoint.
   * </pre>
   *
   * <code>int32 code = 7;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * empty on success, error message on failure
   * </pre>
   *
   * <code>string msg = 8;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   * empty on success, error message on failure
   * </pre>
   *
   * <code>string msg = 8;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <pre>
   * parsed target (only for internal users)
   * </pre>
   *
   * <code>string question = 9;</code>
   * @return The question.
   */
  java.lang.String getQuestion();
  /**
   * <pre>
   * parsed target (only for internal users)
   * </pre>
   *
   * <code>string question = 9;</code>
   * @return The bytes for question.
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <pre>
   * solver sub-type (objectClick, 33, etc.)
   * </pre>
   *
   * <code>string questionType = 10;</code>
   * @return The questionType.
   */
  java.lang.String getQuestionType();
  /**
   * <pre>
   * solver sub-type (objectClick, 33, etc.)
   * </pre>
   *
   * <code>string questionType = 10;</code>
   * @return The bytes for questionType.
   */
  com.google.protobuf.ByteString
      getQuestionTypeBytes();

  /**
   * <pre>
   * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
   * Returned when a video captcha target is detected but the client has
   * not yet sent video frame data.  Must match REST JSON shape exactly.
   * </pre>
   *
   * <code>string questionVariant = 11;</code>
   * @return The questionVariant.
   */
  java.lang.String getQuestionVariant();
  /**
   * <pre>
   * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
   * Returned when a video captcha target is detected but the client has
   * not yet sent video frame data.  Must match REST JSON shape exactly.
   * </pre>
   *
   * <code>string questionVariant = 11;</code>
   * @return The bytes for questionVariant.
   */
  com.google.protobuf.ByteString
      getQuestionVariantBytes();

  /**
   * <pre>
   * 0
   * </pre>
   *
   * <code>int32 retryAfterSec = 12;</code>
   * @return The retryAfterSec.
   */
  int getRetryAfterSec();

  /**
   * <pre>
   * true when video data needed
   * </pre>
   *
   * <code>bool video = 13;</code>
   * @return The video.
   */
  boolean getVideo();

  /**
   * <pre>
   * format/duration/frames spec
   * </pre>
   *
   * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
   * @return Whether the canvasParams field is set.
   */
  boolean hasCanvasParams();
  /**
   * <pre>
   * format/duration/frames spec
   * </pre>
   *
   * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
   * @return The canvasParams.
   */
  com.captchasonic.v1.VideoCanvasParams getCanvasParams();
  /**
   * <pre>
   * format/duration/frames spec
   * </pre>
   *
   * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
   */
  com.captchasonic.v1.VideoCanvasParamsOrBuilder getCanvasParamsOrBuilder();

  /**
   * <pre>
   * echoed frame indices (top-level)
   * </pre>
   *
   * <code>repeated int32 frames = 15;</code>
   * @return A list containing the frames.
   */
  java.util.List<java.lang.Integer> getFramesList();
  /**
   * <pre>
   * echoed frame indices (top-level)
   * </pre>
   *
   * <code>repeated int32 frames = 15;</code>
   * @return The count of frames.
   */
  int getFramesCount();
  /**
   * <pre>
   * echoed frame indices (top-level)
   * </pre>
   *
   * <code>repeated int32 frames = 15;</code>
   * @param index The index of the element to return.
   * @return The frames at the given index.
   */
  int getFrames(int index);

  /**
   * <pre>
   * total frame count (top-level)
   * </pre>
   *
   * <code>optional int32 framecount = 16;</code>
   * @return Whether the framecount field is set.
   */
  boolean hasFramecount();
  /**
   * <pre>
   * total frame count (top-level)
   * </pre>
   *
   * <code>optional int32 framecount = 16;</code>
   * @return The framecount.
   */
  int getFramecount();
}
