// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

/**
 * Protobuf type {@code captchasonic.v1.CreateTaskResponse}
 */
@com.google.protobuf.Generated
public final class CreateTaskResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:captchasonic.v1.CreateTaskResponse)
    CreateTaskResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "CreateTaskResponse");
  }
  // Use CreateTaskResponse.newBuilder() to construct.
  private CreateTaskResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateTaskResponse() {
    errorDescription_ = "";
    taskId_ = "";
    status_ = "";
    msg_ = "";
    question_ = "";
    questionType_ = "";
    questionVariant_ = "";
    frames_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 4:
        return internalGetSolution();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.captchasonic.v1.CreateTaskResponse.class, com.captchasonic.v1.CreateTaskResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ERRORID_FIELD_NUMBER = 1;
  private int errorId_ = 0;
  /**
   * <code>int32 errorId = 1;</code>
   * @return The errorId.
   */
  @java.lang.Override
  public int getErrorId() {
    return errorId_;
  }

  public static final int ERRORDESCRIPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorDescription_ = "";
  /**
   * <code>string errorDescription = 2;</code>
   * @return The errorDescription.
   */
  @java.lang.Override
  public java.lang.String getErrorDescription() {
    java.lang.Object ref = errorDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorDescription_ = s;
      return s;
    }
  }
  /**
   * <code>string errorDescription = 2;</code>
   * @return The bytes for errorDescription.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorDescriptionBytes() {
    java.lang.Object ref = errorDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASKID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskId_ = "";
  /**
   * <code>string taskId = 3;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string taskId = 3;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOLUTION_FIELD_NUMBER = 4;
  private static final class SolutionDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskResponse_SolutionEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> solution_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetSolution() {
    if (solution_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SolutionDefaultEntryHolder.defaultEntry);
    }
    return solution_;
  }
  public int getSolutionCount() {
    return internalGetSolution().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  @java.lang.Override
  public boolean containsSolution(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetSolution().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSolutionMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getSolution() {
    return getSolutionMap();
  }
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getSolutionMap() {
    return internalGetSolution().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getSolutionOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSolution().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; solution = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getSolutionOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetSolution().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPED_SOLUTION_FIELD_NUMBER = 6;
  private com.captchasonic.v1.SolutionPayload typedSolution_;
  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
   * @return Whether the typedSolution field is set.
   */
  @java.lang.Override
  public boolean hasTypedSolution() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
   * @return The typedSolution.
   */
  @java.lang.Override
  public com.captchasonic.v1.SolutionPayload getTypedSolution() {
    return typedSolution_ == null ? com.captchasonic.v1.SolutionPayload.getDefaultInstance() : typedSolution_;
  }
  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.SolutionPayloadOrBuilder getTypedSolutionOrBuilder() {
    return typedSolution_ == null ? com.captchasonic.v1.SolutionPayload.getDefaultInstance() : typedSolution_;
  }

  public static final int CODE_FIELD_NUMBER = 7;
  private int code_ = 0;
  /**
   * <pre>
   * ── REST parity fields ──────────────────────────────────────────────
   * Extension expects same response shape as HTTP endpoint.
   * </pre>
   *
   * <code>int32 code = 7;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int MSG_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msg_ = "";
  /**
   * <pre>
   * empty on success, error message on failure
   * </pre>
   *
   * <code>string msg = 8;</code>
   * @return The msg.
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * empty on success, error message on failure
   * </pre>
   *
   * <code>string msg = 8;</code>
   * @return The bytes for msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTION_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object question_ = "";
  /**
   * <pre>
   * parsed target (only for internal users)
   * </pre>
   *
   * <code>string question = 9;</code>
   * @return The question.
   */
  @java.lang.Override
  public java.lang.String getQuestion() {
    java.lang.Object ref = question_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      question_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * parsed target (only for internal users)
   * </pre>
   *
   * <code>string question = 9;</code>
   * @return The bytes for question.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuestionBytes() {
    java.lang.Object ref = question_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      question_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTIONTYPE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object questionType_ = "";
  /**
   * <pre>
   * solver sub-type (objectClick, 33, etc.)
   * </pre>
   *
   * <code>string questionType = 10;</code>
   * @return The questionType.
   */
  @java.lang.Override
  public java.lang.String getQuestionType() {
    java.lang.Object ref = questionType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      questionType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * solver sub-type (objectClick, 33, etc.)
   * </pre>
   *
   * <code>string questionType = 10;</code>
   * @return The bytes for questionType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuestionTypeBytes() {
    java.lang.Object ref = questionType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      questionType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTIONVARIANT_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object questionVariant_ = "";
  /**
   * <pre>
   * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
   * Returned when a video captcha target is detected but the client has
   * not yet sent video frame data.  Must match REST JSON shape exactly.
   * </pre>
   *
   * <code>string questionVariant = 11;</code>
   * @return The questionVariant.
   */
  @java.lang.Override
  public java.lang.String getQuestionVariant() {
    java.lang.Object ref = questionVariant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      questionVariant_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
   * Returned when a video captcha target is detected but the client has
   * not yet sent video frame data.  Must match REST JSON shape exactly.
   * </pre>
   *
   * <code>string questionVariant = 11;</code>
   * @return The bytes for questionVariant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuestionVariantBytes() {
    java.lang.Object ref = questionVariant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      questionVariant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETRYAFTERSEC_FIELD_NUMBER = 12;
  private int retryAfterSec_ = 0;
  /**
   * <pre>
   * 0
   * </pre>
   *
   * <code>int32 retryAfterSec = 12;</code>
   * @return The retryAfterSec.
   */
  @java.lang.Override
  public int getRetryAfterSec() {
    return retryAfterSec_;
  }

  public static final int VIDEO_FIELD_NUMBER = 13;
  private boolean video_ = false;
  /**
   * <pre>
   * true when video data needed
   * </pre>
   *
   * <code>bool video = 13;</code>
   * @return The video.
   */
  @java.lang.Override
  public boolean getVideo() {
    return video_;
  }

  public static final int CANVASPARAMS_FIELD_NUMBER = 14;
  private com.captchasonic.v1.VideoCanvasParams canvasParams_;
  /**
   * <pre>
   * format/duration/frames spec
   * </pre>
   *
   * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
   * @return Whether the canvasParams field is set.
   */
  @java.lang.Override
  public boolean hasCanvasParams() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * format/duration/frames spec
   * </pre>
   *
   * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
   * @return The canvasParams.
   */
  @java.lang.Override
  public com.captchasonic.v1.VideoCanvasParams getCanvasParams() {
    return canvasParams_ == null ? com.captchasonic.v1.VideoCanvasParams.getDefaultInstance() : canvasParams_;
  }
  /**
   * <pre>
   * format/duration/frames spec
   * </pre>
   *
   * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.VideoCanvasParamsOrBuilder getCanvasParamsOrBuilder() {
    return canvasParams_ == null ? com.captchasonic.v1.VideoCanvasParams.getDefaultInstance() : canvasParams_;
  }

  public static final int FRAMES_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList frames_ =
      emptyIntList();
  /**
   * <pre>
   * echoed frame indices (top-level)
   * </pre>
   *
   * <code>repeated int32 frames = 15;</code>
   * @return A list containing the frames.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getFramesList() {
    return frames_;
  }
  /**
   * <pre>
   * echoed frame indices (top-level)
   * </pre>
   *
   * <code>repeated int32 frames = 15;</code>
   * @return The count of frames.
   */
  public int getFramesCount() {
    return frames_.size();
  }
  /**
   * <pre>
   * echoed frame indices (top-level)
   * </pre>
   *
   * <code>repeated int32 frames = 15;</code>
   * @param index The index of the element to return.
   * @return The frames at the given index.
   */
  public int getFrames(int index) {
    return frames_.getInt(index);
  }
  private int framesMemoizedSerializedSize = -1;

  public static final int FRAMECOUNT_FIELD_NUMBER = 16;
  private int framecount_ = 0;
  /**
   * <pre>
   * total frame count (top-level)
   * </pre>
   *
   * <code>optional int32 framecount = 16;</code>
   * @return Whether the framecount field is set.
   */
  @java.lang.Override
  public boolean hasFramecount() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * total frame count (top-level)
   * </pre>
   *
   * <code>optional int32 framecount = 16;</code>
   * @return The framecount.
   */
  @java.lang.Override
  public int getFramecount() {
    return framecount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (errorId_ != 0) {
      output.writeInt32(1, errorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorDescription_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, errorDescription_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, taskId_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetSolution(),
        SolutionDefaultEntryHolder.defaultEntry,
        4);
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getTypedSolution());
    }
    if (code_ != 0) {
      output.writeInt32(7, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msg_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, msg_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(question_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, question_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(questionType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, questionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(questionVariant_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, questionVariant_);
    }
    if (retryAfterSec_ != 0) {
      output.writeInt32(12, retryAfterSec_);
    }
    if (video_ != false) {
      output.writeBool(13, video_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(14, getCanvasParams());
    }
    if (getFramesList().size() > 0) {
      output.writeUInt32NoTag(122);
      output.writeUInt32NoTag(framesMemoizedSerializedSize);
    }
    for (int i = 0; i < frames_.size(); i++) {
      output.writeInt32NoTag(frames_.getInt(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(16, framecount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errorId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, errorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorDescription_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, errorDescription_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, taskId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetSolution().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      solution__ = SolutionDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, solution__);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTypedSolution());
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msg_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, msg_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(question_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, question_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(questionType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, questionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(questionVariant_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, questionVariant_);
    }
    if (retryAfterSec_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, retryAfterSec_);
    }
    if (video_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, video_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getCanvasParams());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < frames_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(frames_.getInt(i));
      }
      size += dataSize;
      if (!getFramesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      framesMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, framecount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.captchasonic.v1.CreateTaskResponse)) {
      return super.equals(obj);
    }
    com.captchasonic.v1.CreateTaskResponse other = (com.captchasonic.v1.CreateTaskResponse) obj;

    if (getErrorId()
        != other.getErrorId()) return false;
    if (!getErrorDescription()
        .equals(other.getErrorDescription())) return false;
    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (!internalGetSolution().equals(
        other.internalGetSolution())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (hasTypedSolution() != other.hasTypedSolution()) return false;
    if (hasTypedSolution()) {
      if (!getTypedSolution()
          .equals(other.getTypedSolution())) return false;
    }
    if (getCode()
        != other.getCode()) return false;
    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (!getQuestion()
        .equals(other.getQuestion())) return false;
    if (!getQuestionType()
        .equals(other.getQuestionType())) return false;
    if (!getQuestionVariant()
        .equals(other.getQuestionVariant())) return false;
    if (getRetryAfterSec()
        != other.getRetryAfterSec()) return false;
    if (getVideo()
        != other.getVideo()) return false;
    if (hasCanvasParams() != other.hasCanvasParams()) return false;
    if (hasCanvasParams()) {
      if (!getCanvasParams()
          .equals(other.getCanvasParams())) return false;
    }
    if (!getFramesList()
        .equals(other.getFramesList())) return false;
    if (hasFramecount() != other.hasFramecount()) return false;
    if (hasFramecount()) {
      if (getFramecount()
          != other.getFramecount()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERRORID_FIELD_NUMBER;
    hash = (53 * hash) + getErrorId();
    hash = (37 * hash) + ERRORDESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getErrorDescription().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    if (!internalGetSolution().getMap().isEmpty()) {
      hash = (37 * hash) + SOLUTION_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSolution().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (hasTypedSolution()) {
      hash = (37 * hash) + TYPED_SOLUTION_FIELD_NUMBER;
      hash = (53 * hash) + getTypedSolution().hashCode();
    }
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (37 * hash) + QUESTION_FIELD_NUMBER;
    hash = (53 * hash) + getQuestion().hashCode();
    hash = (37 * hash) + QUESTIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getQuestionType().hashCode();
    hash = (37 * hash) + QUESTIONVARIANT_FIELD_NUMBER;
    hash = (53 * hash) + getQuestionVariant().hashCode();
    hash = (37 * hash) + RETRYAFTERSEC_FIELD_NUMBER;
    hash = (53 * hash) + getRetryAfterSec();
    hash = (37 * hash) + VIDEO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getVideo());
    if (hasCanvasParams()) {
      hash = (37 * hash) + CANVASPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getCanvasParams().hashCode();
    }
    if (getFramesCount() > 0) {
      hash = (37 * hash) + FRAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFramesList().hashCode();
    }
    if (hasFramecount()) {
      hash = (37 * hash) + FRAMECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getFramecount();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.captchasonic.v1.CreateTaskResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.captchasonic.v1.CreateTaskResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.CreateTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.captchasonic.v1.CreateTaskResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code captchasonic.v1.CreateTaskResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:captchasonic.v1.CreateTaskResponse)
      com.captchasonic.v1.CreateTaskResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetSolution();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableSolution();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.captchasonic.v1.CreateTaskResponse.class, com.captchasonic.v1.CreateTaskResponse.Builder.class);
    }

    // Construct using com.captchasonic.v1.CreateTaskResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTypedSolutionFieldBuilder();
        internalGetCanvasParamsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      errorId_ = 0;
      errorDescription_ = "";
      taskId_ = "";
      internalGetMutableSolution().clear();
      status_ = "";
      typedSolution_ = null;
      if (typedSolutionBuilder_ != null) {
        typedSolutionBuilder_.dispose();
        typedSolutionBuilder_ = null;
      }
      code_ = 0;
      msg_ = "";
      question_ = "";
      questionType_ = "";
      questionVariant_ = "";
      retryAfterSec_ = 0;
      video_ = false;
      canvasParams_ = null;
      if (canvasParamsBuilder_ != null) {
        canvasParamsBuilder_.dispose();
        canvasParamsBuilder_ = null;
      }
      frames_ = emptyIntList();
      framecount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskResponse_descriptor;
    }

    @java.lang.Override
    public com.captchasonic.v1.CreateTaskResponse getDefaultInstanceForType() {
      return com.captchasonic.v1.CreateTaskResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.captchasonic.v1.CreateTaskResponse build() {
      com.captchasonic.v1.CreateTaskResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.captchasonic.v1.CreateTaskResponse buildPartial() {
      com.captchasonic.v1.CreateTaskResponse result = new com.captchasonic.v1.CreateTaskResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.captchasonic.v1.CreateTaskResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.errorId_ = errorId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.errorDescription_ = errorDescription_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.taskId_ = taskId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.solution_ = internalGetSolution();
        result.solution_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.typedSolution_ = typedSolutionBuilder_ == null
            ? typedSolution_
            : typedSolutionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.msg_ = msg_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.question_ = question_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.questionType_ = questionType_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.questionVariant_ = questionVariant_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.retryAfterSec_ = retryAfterSec_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.video_ = video_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.canvasParams_ = canvasParamsBuilder_ == null
            ? canvasParams_
            : canvasParamsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        frames_.makeImmutable();
        result.frames_ = frames_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.framecount_ = framecount_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.captchasonic.v1.CreateTaskResponse) {
        return mergeFrom((com.captchasonic.v1.CreateTaskResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.captchasonic.v1.CreateTaskResponse other) {
      if (other == com.captchasonic.v1.CreateTaskResponse.getDefaultInstance()) return this;
      if (other.getErrorId() != 0) {
        setErrorId(other.getErrorId());
      }
      if (!other.getErrorDescription().isEmpty()) {
        errorDescription_ = other.errorDescription_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      internalGetMutableSolution().mergeFrom(
          other.internalGetSolution());
      bitField0_ |= 0x00000008;
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasTypedSolution()) {
        mergeTypedSolution(other.getTypedSolution());
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getQuestion().isEmpty()) {
        question_ = other.question_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getQuestionType().isEmpty()) {
        questionType_ = other.questionType_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getQuestionVariant().isEmpty()) {
        questionVariant_ = other.questionVariant_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.getRetryAfterSec() != 0) {
        setRetryAfterSec(other.getRetryAfterSec());
      }
      if (other.getVideo() != false) {
        setVideo(other.getVideo());
      }
      if (other.hasCanvasParams()) {
        mergeCanvasParams(other.getCanvasParams());
      }
      if (!other.frames_.isEmpty()) {
        if (frames_.isEmpty()) {
          frames_ = other.frames_;
          frames_.makeImmutable();
          bitField0_ |= 0x00004000;
        } else {
          ensureFramesIsMutable();
          frames_.addAll(other.frames_);
        }
        onChanged();
      }
      if (other.hasFramecount()) {
        setFramecount(other.getFramecount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              errorId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              errorDescription_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              solution__ = input.readMessage(
                  SolutionDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableSolution().getMutableMap().put(
                  solution__.getKey(), solution__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetTypedSolutionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              code_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              msg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              question_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              questionType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              questionVariant_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              retryAfterSec_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              video_ = input.readBool();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 114: {
              input.readMessage(
                  internalGetCanvasParamsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 120: {
              int v = input.readInt32();
              ensureFramesIsMutable();
              frames_.addInt(v);
              break;
            } // case 120
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureFramesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                frames_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 122
            case 128: {
              framecount_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int errorId_ ;
    /**
     * <code>int32 errorId = 1;</code>
     * @return The errorId.
     */
    @java.lang.Override
    public int getErrorId() {
      return errorId_;
    }
    /**
     * <code>int32 errorId = 1;</code>
     * @param value The errorId to set.
     * @return This builder for chaining.
     */
    public Builder setErrorId(int value) {

      errorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 errorId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      errorId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorDescription_ = "";
    /**
     * <code>string errorDescription = 2;</code>
     * @return The errorDescription.
     */
    public java.lang.String getErrorDescription() {
      java.lang.Object ref = errorDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errorDescription = 2;</code>
     * @return The bytes for errorDescription.
     */
    public com.google.protobuf.ByteString
        getErrorDescriptionBytes() {
      java.lang.Object ref = errorDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errorDescription = 2;</code>
     * @param value The errorDescription to set.
     * @return This builder for chaining.
     */
    public Builder setErrorDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorDescription_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string errorDescription = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorDescription() {
      errorDescription_ = getDefaultInstance().getErrorDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string errorDescription = 2;</code>
     * @param value The bytes for errorDescription to set.
     * @return This builder for chaining.
     */
    public Builder setErrorDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorDescription_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <code>string taskId = 3;</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string taskId = 3;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string taskId = 3;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string taskId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string taskId = 3;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> solution_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetSolution() {
      if (solution_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SolutionDefaultEntryHolder.defaultEntry);
      }
      return solution_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableSolution() {
      if (solution_ == null) {
        solution_ = com.google.protobuf.MapField.newMapField(
            SolutionDefaultEntryHolder.defaultEntry);
      }
      if (!solution_.isMutable()) {
        solution_ = solution_.copy();
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return solution_;
    }
    public int getSolutionCount() {
      return internalGetSolution().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; solution = 4;</code>
     */
    @java.lang.Override
    public boolean containsSolution(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSolution().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSolutionMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSolution() {
      return getSolutionMap();
    }
    /**
     * <code>map&lt;string, string&gt; solution = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getSolutionMap() {
      return internalGetSolution().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; solution = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getSolutionOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSolution().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; solution = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getSolutionOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSolution().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearSolution() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableSolution().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; solution = 4;</code>
     */
    public Builder removeSolution(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableSolution().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableSolution() {
      bitField0_ |= 0x00000008;
      return internalGetMutableSolution().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; solution = 4;</code>
     */
    public Builder putSolution(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableSolution().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; solution = 4;</code>
     */
    public Builder putAllSolution(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableSolution().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 5;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.captchasonic.v1.SolutionPayload typedSolution_;
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.SolutionPayload, com.captchasonic.v1.SolutionPayload.Builder, com.captchasonic.v1.SolutionPayloadOrBuilder> typedSolutionBuilder_;
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     * @return Whether the typedSolution field is set.
     */
    public boolean hasTypedSolution() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     * @return The typedSolution.
     */
    public com.captchasonic.v1.SolutionPayload getTypedSolution() {
      if (typedSolutionBuilder_ == null) {
        return typedSolution_ == null ? com.captchasonic.v1.SolutionPayload.getDefaultInstance() : typedSolution_;
      } else {
        return typedSolutionBuilder_.getMessage();
      }
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     */
    public Builder setTypedSolution(com.captchasonic.v1.SolutionPayload value) {
      if (typedSolutionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        typedSolution_ = value;
      } else {
        typedSolutionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     */
    public Builder setTypedSolution(
        com.captchasonic.v1.SolutionPayload.Builder builderForValue) {
      if (typedSolutionBuilder_ == null) {
        typedSolution_ = builderForValue.build();
      } else {
        typedSolutionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     */
    public Builder mergeTypedSolution(com.captchasonic.v1.SolutionPayload value) {
      if (typedSolutionBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          typedSolution_ != null &&
          typedSolution_ != com.captchasonic.v1.SolutionPayload.getDefaultInstance()) {
          getTypedSolutionBuilder().mergeFrom(value);
        } else {
          typedSolution_ = value;
        }
      } else {
        typedSolutionBuilder_.mergeFrom(value);
      }
      if (typedSolution_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     */
    public Builder clearTypedSolution() {
      bitField0_ = (bitField0_ & ~0x00000020);
      typedSolution_ = null;
      if (typedSolutionBuilder_ != null) {
        typedSolutionBuilder_.dispose();
        typedSolutionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     */
    public com.captchasonic.v1.SolutionPayload.Builder getTypedSolutionBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetTypedSolutionFieldBuilder().getBuilder();
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     */
    public com.captchasonic.v1.SolutionPayloadOrBuilder getTypedSolutionOrBuilder() {
      if (typedSolutionBuilder_ != null) {
        return typedSolutionBuilder_.getMessageOrBuilder();
      } else {
        return typedSolution_ == null ?
            com.captchasonic.v1.SolutionPayload.getDefaultInstance() : typedSolution_;
      }
    }
    /**
     * <code>.captchasonic.v1.SolutionPayload typed_solution = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.SolutionPayload, com.captchasonic.v1.SolutionPayload.Builder, com.captchasonic.v1.SolutionPayloadOrBuilder> 
        internalGetTypedSolutionFieldBuilder() {
      if (typedSolutionBuilder_ == null) {
        typedSolutionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.SolutionPayload, com.captchasonic.v1.SolutionPayload.Builder, com.captchasonic.v1.SolutionPayloadOrBuilder>(
                getTypedSolution(),
                getParentForChildren(),
                isClean());
        typedSolution_ = null;
      }
      return typedSolutionBuilder_;
    }

    private int code_ ;
    /**
     * <pre>
     * ── REST parity fields ──────────────────────────────────────────────
     * Extension expects same response shape as HTTP endpoint.
     * </pre>
     *
     * <code>int32 code = 7;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     * ── REST parity fields ──────────────────────────────────────────────
     * Extension expects same response shape as HTTP endpoint.
     * </pre>
     *
     * <code>int32 code = 7;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {

      code_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ── REST parity fields ──────────────────────────────────────────────
     * Extension expects same response shape as HTTP endpoint.
     * </pre>
     *
     * <code>int32 code = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000040);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <pre>
     * empty on success, error message on failure
     * </pre>
     *
     * <code>string msg = 8;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * empty on success, error message on failure
     * </pre>
     *
     * <code>string msg = 8;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * empty on success, error message on failure
     * </pre>
     *
     * <code>string msg = 8;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msg_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * empty on success, error message on failure
     * </pre>
     *
     * <code>string msg = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      msg_ = getDefaultInstance().getMsg();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * empty on success, error message on failure
     * </pre>
     *
     * <code>string msg = 8;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msg_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object question_ = "";
    /**
     * <pre>
     * parsed target (only for internal users)
     * </pre>
     *
     * <code>string question = 9;</code>
     * @return The question.
     */
    public java.lang.String getQuestion() {
      java.lang.Object ref = question_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        question_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * parsed target (only for internal users)
     * </pre>
     *
     * <code>string question = 9;</code>
     * @return The bytes for question.
     */
    public com.google.protobuf.ByteString
        getQuestionBytes() {
      java.lang.Object ref = question_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        question_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * parsed target (only for internal users)
     * </pre>
     *
     * <code>string question = 9;</code>
     * @param value The question to set.
     * @return This builder for chaining.
     */
    public Builder setQuestion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      question_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * parsed target (only for internal users)
     * </pre>
     *
     * <code>string question = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuestion() {
      question_ = getDefaultInstance().getQuestion();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * parsed target (only for internal users)
     * </pre>
     *
     * <code>string question = 9;</code>
     * @param value The bytes for question to set.
     * @return This builder for chaining.
     */
    public Builder setQuestionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      question_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object questionType_ = "";
    /**
     * <pre>
     * solver sub-type (objectClick, 33, etc.)
     * </pre>
     *
     * <code>string questionType = 10;</code>
     * @return The questionType.
     */
    public java.lang.String getQuestionType() {
      java.lang.Object ref = questionType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        questionType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * solver sub-type (objectClick, 33, etc.)
     * </pre>
     *
     * <code>string questionType = 10;</code>
     * @return The bytes for questionType.
     */
    public com.google.protobuf.ByteString
        getQuestionTypeBytes() {
      java.lang.Object ref = questionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        questionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * solver sub-type (objectClick, 33, etc.)
     * </pre>
     *
     * <code>string questionType = 10;</code>
     * @param value The questionType to set.
     * @return This builder for chaining.
     */
    public Builder setQuestionType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      questionType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * solver sub-type (objectClick, 33, etc.)
     * </pre>
     *
     * <code>string questionType = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuestionType() {
      questionType_ = getDefaultInstance().getQuestionType();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * solver sub-type (objectClick, 33, etc.)
     * </pre>
     *
     * <code>string questionType = 10;</code>
     * @param value The bytes for questionType to set.
     * @return This builder for chaining.
     */
    public Builder setQuestionTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      questionType_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object questionVariant_ = "";
    /**
     * <pre>
     * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
     * Returned when a video captcha target is detected but the client has
     * not yet sent video frame data.  Must match REST JSON shape exactly.
     * </pre>
     *
     * <code>string questionVariant = 11;</code>
     * @return The questionVariant.
     */
    public java.lang.String getQuestionVariant() {
      java.lang.Object ref = questionVariant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        questionVariant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
     * Returned when a video captcha target is detected but the client has
     * not yet sent video frame data.  Must match REST JSON shape exactly.
     * </pre>
     *
     * <code>string questionVariant = 11;</code>
     * @return The bytes for questionVariant.
     */
    public com.google.protobuf.ByteString
        getQuestionVariantBytes() {
      java.lang.Object ref = questionVariant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        questionVariant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
     * Returned when a video captcha target is detected but the client has
     * not yet sent video frame data.  Must match REST JSON shape exactly.
     * </pre>
     *
     * <code>string questionVariant = 11;</code>
     * @param value The questionVariant to set.
     * @return This builder for chaining.
     */
    public Builder setQuestionVariant(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      questionVariant_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
     * Returned when a video captcha target is detected but the client has
     * not yet sent video frame data.  Must match REST JSON shape exactly.
     * </pre>
     *
     * <code>string questionVariant = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuestionVariant() {
      questionVariant_ = getDefaultInstance().getQuestionVariant();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ── Video negotiation (ERROR_VIDEO_PAYLOAD_REQUIRED) ────────────────
     * Returned when a video captcha target is detected but the client has
     * not yet sent video frame data.  Must match REST JSON shape exactly.
     * </pre>
     *
     * <code>string questionVariant = 11;</code>
     * @param value The bytes for questionVariant to set.
     * @return This builder for chaining.
     */
    public Builder setQuestionVariantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      questionVariant_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private int retryAfterSec_ ;
    /**
     * <pre>
     * 0
     * </pre>
     *
     * <code>int32 retryAfterSec = 12;</code>
     * @return The retryAfterSec.
     */
    @java.lang.Override
    public int getRetryAfterSec() {
      return retryAfterSec_;
    }
    /**
     * <pre>
     * 0
     * </pre>
     *
     * <code>int32 retryAfterSec = 12;</code>
     * @param value The retryAfterSec to set.
     * @return This builder for chaining.
     */
    public Builder setRetryAfterSec(int value) {

      retryAfterSec_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0
     * </pre>
     *
     * <code>int32 retryAfterSec = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryAfterSec() {
      bitField0_ = (bitField0_ & ~0x00000800);
      retryAfterSec_ = 0;
      onChanged();
      return this;
    }

    private boolean video_ ;
    /**
     * <pre>
     * true when video data needed
     * </pre>
     *
     * <code>bool video = 13;</code>
     * @return The video.
     */
    @java.lang.Override
    public boolean getVideo() {
      return video_;
    }
    /**
     * <pre>
     * true when video data needed
     * </pre>
     *
     * <code>bool video = 13;</code>
     * @param value The video to set.
     * @return This builder for chaining.
     */
    public Builder setVideo(boolean value) {

      video_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * true when video data needed
     * </pre>
     *
     * <code>bool video = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideo() {
      bitField0_ = (bitField0_ & ~0x00001000);
      video_ = false;
      onChanged();
      return this;
    }

    private com.captchasonic.v1.VideoCanvasParams canvasParams_;
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.VideoCanvasParams, com.captchasonic.v1.VideoCanvasParams.Builder, com.captchasonic.v1.VideoCanvasParamsOrBuilder> canvasParamsBuilder_;
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     * @return Whether the canvasParams field is set.
     */
    public boolean hasCanvasParams() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     * @return The canvasParams.
     */
    public com.captchasonic.v1.VideoCanvasParams getCanvasParams() {
      if (canvasParamsBuilder_ == null) {
        return canvasParams_ == null ? com.captchasonic.v1.VideoCanvasParams.getDefaultInstance() : canvasParams_;
      } else {
        return canvasParamsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     */
    public Builder setCanvasParams(com.captchasonic.v1.VideoCanvasParams value) {
      if (canvasParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        canvasParams_ = value;
      } else {
        canvasParamsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     */
    public Builder setCanvasParams(
        com.captchasonic.v1.VideoCanvasParams.Builder builderForValue) {
      if (canvasParamsBuilder_ == null) {
        canvasParams_ = builderForValue.build();
      } else {
        canvasParamsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     */
    public Builder mergeCanvasParams(com.captchasonic.v1.VideoCanvasParams value) {
      if (canvasParamsBuilder_ == null) {
        if (((bitField0_ & 0x00002000) != 0) &&
          canvasParams_ != null &&
          canvasParams_ != com.captchasonic.v1.VideoCanvasParams.getDefaultInstance()) {
          getCanvasParamsBuilder().mergeFrom(value);
        } else {
          canvasParams_ = value;
        }
      } else {
        canvasParamsBuilder_.mergeFrom(value);
      }
      if (canvasParams_ != null) {
        bitField0_ |= 0x00002000;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     */
    public Builder clearCanvasParams() {
      bitField0_ = (bitField0_ & ~0x00002000);
      canvasParams_ = null;
      if (canvasParamsBuilder_ != null) {
        canvasParamsBuilder_.dispose();
        canvasParamsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     */
    public com.captchasonic.v1.VideoCanvasParams.Builder getCanvasParamsBuilder() {
      bitField0_ |= 0x00002000;
      onChanged();
      return internalGetCanvasParamsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     */
    public com.captchasonic.v1.VideoCanvasParamsOrBuilder getCanvasParamsOrBuilder() {
      if (canvasParamsBuilder_ != null) {
        return canvasParamsBuilder_.getMessageOrBuilder();
      } else {
        return canvasParams_ == null ?
            com.captchasonic.v1.VideoCanvasParams.getDefaultInstance() : canvasParams_;
      }
    }
    /**
     * <pre>
     * format/duration/frames spec
     * </pre>
     *
     * <code>.captchasonic.v1.VideoCanvasParams canvasParams = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.VideoCanvasParams, com.captchasonic.v1.VideoCanvasParams.Builder, com.captchasonic.v1.VideoCanvasParamsOrBuilder> 
        internalGetCanvasParamsFieldBuilder() {
      if (canvasParamsBuilder_ == null) {
        canvasParamsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.VideoCanvasParams, com.captchasonic.v1.VideoCanvasParams.Builder, com.captchasonic.v1.VideoCanvasParamsOrBuilder>(
                getCanvasParams(),
                getParentForChildren(),
                isClean());
        canvasParams_ = null;
      }
      return canvasParamsBuilder_;
    }

    private com.google.protobuf.Internal.IntList frames_ = emptyIntList();
    private void ensureFramesIsMutable() {
      if (!frames_.isModifiable()) {
        frames_ = makeMutableCopy(frames_);
      }
      bitField0_ |= 0x00004000;
    }
    /**
     * <pre>
     * echoed frame indices (top-level)
     * </pre>
     *
     * <code>repeated int32 frames = 15;</code>
     * @return A list containing the frames.
     */
    public java.util.List<java.lang.Integer>
        getFramesList() {
      frames_.makeImmutable();
      return frames_;
    }
    /**
     * <pre>
     * echoed frame indices (top-level)
     * </pre>
     *
     * <code>repeated int32 frames = 15;</code>
     * @return The count of frames.
     */
    public int getFramesCount() {
      return frames_.size();
    }
    /**
     * <pre>
     * echoed frame indices (top-level)
     * </pre>
     *
     * <code>repeated int32 frames = 15;</code>
     * @param index The index of the element to return.
     * @return The frames at the given index.
     */
    public int getFrames(int index) {
      return frames_.getInt(index);
    }
    /**
     * <pre>
     * echoed frame indices (top-level)
     * </pre>
     *
     * <code>repeated int32 frames = 15;</code>
     * @param index The index to set the value at.
     * @param value The frames to set.
     * @return This builder for chaining.
     */
    public Builder setFrames(
        int index, int value) {

      ensureFramesIsMutable();
      frames_.setInt(index, value);
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * echoed frame indices (top-level)
     * </pre>
     *
     * <code>repeated int32 frames = 15;</code>
     * @param value The frames to add.
     * @return This builder for chaining.
     */
    public Builder addFrames(int value) {

      ensureFramesIsMutable();
      frames_.addInt(value);
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * echoed frame indices (top-level)
     * </pre>
     *
     * <code>repeated int32 frames = 15;</code>
     * @param values The frames to add.
     * @return This builder for chaining.
     */
    public Builder addAllFrames(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureFramesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, frames_);
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * echoed frame indices (top-level)
     * </pre>
     *
     * <code>repeated int32 frames = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrames() {
      frames_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }

    private int framecount_ ;
    /**
     * <pre>
     * total frame count (top-level)
     * </pre>
     *
     * <code>optional int32 framecount = 16;</code>
     * @return Whether the framecount field is set.
     */
    @java.lang.Override
    public boolean hasFramecount() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <pre>
     * total frame count (top-level)
     * </pre>
     *
     * <code>optional int32 framecount = 16;</code>
     * @return The framecount.
     */
    @java.lang.Override
    public int getFramecount() {
      return framecount_;
    }
    /**
     * <pre>
     * total frame count (top-level)
     * </pre>
     *
     * <code>optional int32 framecount = 16;</code>
     * @param value The framecount to set.
     * @return This builder for chaining.
     */
    public Builder setFramecount(int value) {

      framecount_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * total frame count (top-level)
     * </pre>
     *
     * <code>optional int32 framecount = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearFramecount() {
      bitField0_ = (bitField0_ & ~0x00008000);
      framecount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:captchasonic.v1.CreateTaskResponse)
  }

  // @@protoc_insertion_point(class_scope:captchasonic.v1.CreateTaskResponse)
  private static final com.captchasonic.v1.CreateTaskResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.captchasonic.v1.CreateTaskResponse();
  }

  public static com.captchasonic.v1.CreateTaskResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTaskResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateTaskResponse>() {
    @java.lang.Override
    public CreateTaskResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTaskResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTaskResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.captchasonic.v1.CreateTaskResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

