// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

/**
 * Protobuf type {@code captchasonic.v1.CreateTaskRequest}
 */
@com.google.protobuf.Generated
public final class CreateTaskRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:captchasonic.v1.CreateTaskRequest)
    CreateTaskRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "CreateTaskRequest");
  }
  // Use CreateTaskRequest.newBuilder() to construct.
  private CreateTaskRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateTaskRequest() {
    apiKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.captchasonic.v1.CreateTaskRequest.class, com.captchasonic.v1.CreateTaskRequest.Builder.class);
  }

  private int bitField0_;
  public static final int APIKEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object apiKey_ = "";
  /**
   * <code>string apiKey = 1;</code>
   * @return The apiKey.
   */
  @java.lang.Override
  public java.lang.String getApiKey() {
    java.lang.Object ref = apiKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apiKey_ = s;
      return s;
    }
  }
  /**
   * <code>string apiKey = 1;</code>
   * @return The bytes for apiKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApiKeyBytes() {
    java.lang.Object ref = apiKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apiKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_FIELD_NUMBER = 2;
  private com.captchasonic.v1.Task task_;
  /**
   * <code>.captchasonic.v1.Task task = 2;</code>
   * @return Whether the task field is set.
   */
  @java.lang.Override
  public boolean hasTask() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.captchasonic.v1.Task task = 2;</code>
   * @return The task.
   */
  @java.lang.Override
  public com.captchasonic.v1.Task getTask() {
    return task_ == null ? com.captchasonic.v1.Task.getDefaultInstance() : task_;
  }
  /**
   * <code>.captchasonic.v1.Task task = 2;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.TaskOrBuilder getTaskOrBuilder() {
    return task_ == null ? com.captchasonic.v1.Task.getDefaultInstance() : task_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(apiKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, apiKey_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTask());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(apiKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, apiKey_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTask());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.captchasonic.v1.CreateTaskRequest)) {
      return super.equals(obj);
    }
    com.captchasonic.v1.CreateTaskRequest other = (com.captchasonic.v1.CreateTaskRequest) obj;

    if (!getApiKey()
        .equals(other.getApiKey())) return false;
    if (hasTask() != other.hasTask()) return false;
    if (hasTask()) {
      if (!getTask()
          .equals(other.getTask())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APIKEY_FIELD_NUMBER;
    hash = (53 * hash) + getApiKey().hashCode();
    if (hasTask()) {
      hash = (37 * hash) + TASK_FIELD_NUMBER;
      hash = (53 * hash) + getTask().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.captchasonic.v1.CreateTaskRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.captchasonic.v1.CreateTaskRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.CreateTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.captchasonic.v1.CreateTaskRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code captchasonic.v1.CreateTaskRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:captchasonic.v1.CreateTaskRequest)
      com.captchasonic.v1.CreateTaskRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.captchasonic.v1.CreateTaskRequest.class, com.captchasonic.v1.CreateTaskRequest.Builder.class);
    }

    // Construct using com.captchasonic.v1.CreateTaskRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTaskFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      apiKey_ = "";
      task_ = null;
      if (taskBuilder_ != null) {
        taskBuilder_.dispose();
        taskBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_CreateTaskRequest_descriptor;
    }

    @java.lang.Override
    public com.captchasonic.v1.CreateTaskRequest getDefaultInstanceForType() {
      return com.captchasonic.v1.CreateTaskRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.captchasonic.v1.CreateTaskRequest build() {
      com.captchasonic.v1.CreateTaskRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.captchasonic.v1.CreateTaskRequest buildPartial() {
      com.captchasonic.v1.CreateTaskRequest result = new com.captchasonic.v1.CreateTaskRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.captchasonic.v1.CreateTaskRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.apiKey_ = apiKey_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.task_ = taskBuilder_ == null
            ? task_
            : taskBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.captchasonic.v1.CreateTaskRequest) {
        return mergeFrom((com.captchasonic.v1.CreateTaskRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.captchasonic.v1.CreateTaskRequest other) {
      if (other == com.captchasonic.v1.CreateTaskRequest.getDefaultInstance()) return this;
      if (!other.getApiKey().isEmpty()) {
        apiKey_ = other.apiKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTask()) {
        mergeTask(other.getTask());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              apiKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetTaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object apiKey_ = "";
    /**
     * <code>string apiKey = 1;</code>
     * @return The apiKey.
     */
    public java.lang.String getApiKey() {
      java.lang.Object ref = apiKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string apiKey = 1;</code>
     * @return The bytes for apiKey.
     */
    public com.google.protobuf.ByteString
        getApiKeyBytes() {
      java.lang.Object ref = apiKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string apiKey = 1;</code>
     * @param value The apiKey to set.
     * @return This builder for chaining.
     */
    public Builder setApiKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      apiKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string apiKey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiKey() {
      apiKey_ = getDefaultInstance().getApiKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string apiKey = 1;</code>
     * @param value The bytes for apiKey to set.
     * @return This builder for chaining.
     */
    public Builder setApiKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      apiKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.captchasonic.v1.Task task_;
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.Task, com.captchasonic.v1.Task.Builder, com.captchasonic.v1.TaskOrBuilder> taskBuilder_;
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     * @return Whether the task field is set.
     */
    public boolean hasTask() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     * @return The task.
     */
    public com.captchasonic.v1.Task getTask() {
      if (taskBuilder_ == null) {
        return task_ == null ? com.captchasonic.v1.Task.getDefaultInstance() : task_;
      } else {
        return taskBuilder_.getMessage();
      }
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     */
    public Builder setTask(com.captchasonic.v1.Task value) {
      if (taskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        task_ = value;
      } else {
        taskBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     */
    public Builder setTask(
        com.captchasonic.v1.Task.Builder builderForValue) {
      if (taskBuilder_ == null) {
        task_ = builderForValue.build();
      } else {
        taskBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     */
    public Builder mergeTask(com.captchasonic.v1.Task value) {
      if (taskBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          task_ != null &&
          task_ != com.captchasonic.v1.Task.getDefaultInstance()) {
          getTaskBuilder().mergeFrom(value);
        } else {
          task_ = value;
        }
      } else {
        taskBuilder_.mergeFrom(value);
      }
      if (task_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     */
    public Builder clearTask() {
      bitField0_ = (bitField0_ & ~0x00000002);
      task_ = null;
      if (taskBuilder_ != null) {
        taskBuilder_.dispose();
        taskBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     */
    public com.captchasonic.v1.Task.Builder getTaskBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetTaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     */
    public com.captchasonic.v1.TaskOrBuilder getTaskOrBuilder() {
      if (taskBuilder_ != null) {
        return taskBuilder_.getMessageOrBuilder();
      } else {
        return task_ == null ?
            com.captchasonic.v1.Task.getDefaultInstance() : task_;
      }
    }
    /**
     * <code>.captchasonic.v1.Task task = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.Task, com.captchasonic.v1.Task.Builder, com.captchasonic.v1.TaskOrBuilder> 
        internalGetTaskFieldBuilder() {
      if (taskBuilder_ == null) {
        taskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.Task, com.captchasonic.v1.Task.Builder, com.captchasonic.v1.TaskOrBuilder>(
                getTask(),
                getParentForChildren(),
                isClean());
        task_ = null;
      }
      return taskBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:captchasonic.v1.CreateTaskRequest)
  }

  // @@protoc_insertion_point(class_scope:captchasonic.v1.CreateTaskRequest)
  private static final com.captchasonic.v1.CreateTaskRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.captchasonic.v1.CreateTaskRequest();
  }

  public static com.captchasonic.v1.CreateTaskRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTaskRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateTaskRequest>() {
    @java.lang.Override
    public CreateTaskRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTaskRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTaskRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.captchasonic.v1.CreateTaskRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

