// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface CreateTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.CreateTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apiKey = 1;</code>
   * @return The apiKey.
   */
  java.lang.String getApiKey();
  /**
   * <code>string apiKey = 1;</code>
   * @return The bytes for apiKey.
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();

  /**
   * <code>.captchasonic.v1.Task task = 2;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.captchasonic.v1.Task task = 2;</code>
   * @return The task.
   */
  com.captchasonic.v1.Task getTask();
  /**
   * <code>.captchasonic.v1.Task task = 2;</code>
   */
  com.captchasonic.v1.TaskOrBuilder getTaskOrBuilder();
}
