// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface GetBalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.GetBalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double balance = 1;</code>
   * @return The balance.
   */
  double getBalance();

  /**
   * <code>int32 errorId = 2;</code>
   * @return The errorId.
   */
  int getErrorId();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
