// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface GetTaskResultResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.GetTaskResultResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 errorId = 1;</code>
   * @return The errorId.
   */
  int getErrorId();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>map&lt;string, string&gt; solution = 3;</code>
   */
  int getSolutionCount();
  /**
   * <code>map&lt;string, string&gt; solution = 3;</code>
   */
  boolean containsSolution(
      java.lang.String key);
  /**
   * Use {@link #getSolutionMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getSolution();
  /**
   * <code>map&lt;string, string&gt; solution = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getSolutionMap();
  /**
   * <code>map&lt;string, string&gt; solution = 3;</code>
   */
  /* nullable */
java.lang.String getSolutionOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; solution = 3;</code>
   */
  java.lang.String getSolutionOrThrow(
      java.lang.String key);

  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 4;</code>
   * @return Whether the typedSolution field is set.
   */
  boolean hasTypedSolution();
  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 4;</code>
   * @return The typedSolution.
   */
  com.captchasonic.v1.SolutionPayload getTypedSolution();
  /**
   * <code>.captchasonic.v1.SolutionPayload typed_solution = 4;</code>
   */
  com.captchasonic.v1.SolutionPayloadOrBuilder getTypedSolutionOrBuilder();
}
