// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface GetTaskResultRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.GetTaskResultRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apiKey = 1;</code>
   * @return The apiKey.
   */
  java.lang.String getApiKey();
  /**
   * <code>string apiKey = 1;</code>
   * @return The bytes for apiKey.
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();

  /**
   * <code>string taskId = 2;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string taskId = 2;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();
}
