// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface GridSolutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.GridSolution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 objects = 1;</code>
   * @return A list containing the objects.
   */
  java.util.List<java.lang.Integer> getObjectsList();
  /**
   * <code>repeated int32 objects = 1;</code>
   * @return The count of objects.
   */
  int getObjectsCount();
  /**
   * <code>repeated int32 objects = 1;</code>
   * @param index The index of the element to return.
   * @return The objects at the given index.
   */
  int getObjects(int index);

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
