// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

/**
 * Protobuf type {@code captchasonic.v1.GridSolution}
 */
@com.google.protobuf.Generated
public final class GridSolution extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:captchasonic.v1.GridSolution)
    GridSolutionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "GridSolution");
  }
  // Use GridSolution.newBuilder() to construct.
  private GridSolution(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GridSolution() {
    objects_ = emptyIntList();
    type_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_GridSolution_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_GridSolution_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_GridSolution_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.captchasonic.v1.GridSolution.class, com.captchasonic.v1.GridSolution.Builder.class);
  }

  public static final int OBJECTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList objects_ =
      emptyIntList();
  /**
   * <code>repeated int32 objects = 1;</code>
   * @return A list containing the objects.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getObjectsList() {
    return objects_;
  }
  /**
   * <code>repeated int32 objects = 1;</code>
   * @return The count of objects.
   */
  public int getObjectsCount() {
    return objects_.size();
  }
  /**
   * <code>repeated int32 objects = 1;</code>
   * @param index The index of the element to return.
   * @return The objects at the given index.
   */
  public int getObjects(int index) {
    return objects_.getInt(index);
  }
  private int objectsMemoizedSerializedSize = -1;

  public static final int SIZE_FIELD_NUMBER = 2;
  private int size_ = 0;
  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getObjectsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(objectsMemoizedSerializedSize);
    }
    for (int i = 0; i < objects_.size(); i++) {
      output.writeInt32NoTag(objects_.getInt(i));
    }
    if (size_ != 0) {
      output.writeInt32(2, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, type_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < objects_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(objects_.getInt(i));
      }
      size += dataSize;
      if (!getObjectsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      objectsMemoizedSerializedSize = dataSize;
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, type_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.captchasonic.v1.GridSolution)) {
      return super.equals(obj);
    }
    com.captchasonic.v1.GridSolution other = (com.captchasonic.v1.GridSolution) obj;

    if (!getObjectsList()
        .equals(other.getObjectsList())) return false;
    if (getSize()
        != other.getSize()) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getObjectsCount() > 0) {
      hash = (37 * hash) + OBJECTS_FIELD_NUMBER;
      hash = (53 * hash) + getObjectsList().hashCode();
    }
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.captchasonic.v1.GridSolution parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.captchasonic.v1.GridSolution parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.captchasonic.v1.GridSolution parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.GridSolution parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.captchasonic.v1.GridSolution prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code captchasonic.v1.GridSolution}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:captchasonic.v1.GridSolution)
      com.captchasonic.v1.GridSolutionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_GridSolution_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_GridSolution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.captchasonic.v1.GridSolution.class, com.captchasonic.v1.GridSolution.Builder.class);
    }

    // Construct using com.captchasonic.v1.GridSolution.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      objects_ = emptyIntList();
      size_ = 0;
      type_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_GridSolution_descriptor;
    }

    @java.lang.Override
    public com.captchasonic.v1.GridSolution getDefaultInstanceForType() {
      return com.captchasonic.v1.GridSolution.getDefaultInstance();
    }

    @java.lang.Override
    public com.captchasonic.v1.GridSolution build() {
      com.captchasonic.v1.GridSolution result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.captchasonic.v1.GridSolution buildPartial() {
      com.captchasonic.v1.GridSolution result = new com.captchasonic.v1.GridSolution(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.captchasonic.v1.GridSolution result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        objects_.makeImmutable();
        result.objects_ = objects_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.type_ = type_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.captchasonic.v1.GridSolution) {
        return mergeFrom((com.captchasonic.v1.GridSolution)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.captchasonic.v1.GridSolution other) {
      if (other == com.captchasonic.v1.GridSolution.getDefaultInstance()) return this;
      if (!other.objects_.isEmpty()) {
        if (objects_.isEmpty()) {
          objects_ = other.objects_;
          objects_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureObjectsIsMutable();
          objects_.addAll(other.objects_);
        }
        onChanged();
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readInt32();
              ensureObjectsIsMutable();
              objects_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureObjectsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                objects_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              size_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList objects_ = emptyIntList();
    private void ensureObjectsIsMutable() {
      if (!objects_.isModifiable()) {
        objects_ = makeMutableCopy(objects_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated int32 objects = 1;</code>
     * @return A list containing the objects.
     */
    public java.util.List<java.lang.Integer>
        getObjectsList() {
      objects_.makeImmutable();
      return objects_;
    }
    /**
     * <code>repeated int32 objects = 1;</code>
     * @return The count of objects.
     */
    public int getObjectsCount() {
      return objects_.size();
    }
    /**
     * <code>repeated int32 objects = 1;</code>
     * @param index The index of the element to return.
     * @return The objects at the given index.
     */
    public int getObjects(int index) {
      return objects_.getInt(index);
    }
    /**
     * <code>repeated int32 objects = 1;</code>
     * @param index The index to set the value at.
     * @param value The objects to set.
     * @return This builder for chaining.
     */
    public Builder setObjects(
        int index, int value) {

      ensureObjectsIsMutable();
      objects_.setInt(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 objects = 1;</code>
     * @param value The objects to add.
     * @return This builder for chaining.
     */
    public Builder addObjects(int value) {

      ensureObjectsIsMutable();
      objects_.addInt(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 objects = 1;</code>
     * @param values The objects to add.
     * @return This builder for chaining.
     */
    public Builder addAllObjects(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureObjectsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, objects_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 objects = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjects() {
      objects_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 2;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 2;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {

      size_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      size_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:captchasonic.v1.GridSolution)
  }

  // @@protoc_insertion_point(class_scope:captchasonic.v1.GridSolution)
  private static final com.captchasonic.v1.GridSolution DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.captchasonic.v1.GridSolution();
  }

  public static com.captchasonic.v1.GridSolution getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GridSolution>
      PARSER = new com.google.protobuf.AbstractParser<GridSolution>() {
    @java.lang.Override
    public GridSolution parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GridSolution> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GridSolution> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.captchasonic.v1.GridSolution getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

