// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {
}
