// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool healthy = 1;</code>
   * @return The healthy.
   */
  boolean getHealthy();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
