// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

/**
 * Protobuf type {@code captchasonic.v1.SingleSolution}
 */
@com.google.protobuf.Generated
public final class SingleSolution extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:captchasonic.v1.SingleSolution)
    SingleSolutionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "SingleSolution");
  }
  // Use SingleSolution.newBuilder() to construct.
  private SingleSolution(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SingleSolution() {
    hasObject_ = emptyBooleanList();
    type_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SingleSolution_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SingleSolution_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SingleSolution_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.captchasonic.v1.SingleSolution.class, com.captchasonic.v1.SingleSolution.Builder.class);
  }

  public static final int HAS_OBJECT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.BooleanList hasObject_ =
      emptyBooleanList();
  /**
   * <code>repeated bool has_object = 1;</code>
   * @return A list containing the hasObject.
   */
  @java.lang.Override
  public java.util.List<java.lang.Boolean>
      getHasObjectList() {
    return hasObject_;
  }
  /**
   * <code>repeated bool has_object = 1;</code>
   * @return The count of hasObject.
   */
  public int getHasObjectCount() {
    return hasObject_.size();
  }
  /**
   * <code>repeated bool has_object = 1;</code>
   * @param index The index of the element to return.
   * @return The hasObject at the given index.
   */
  public boolean getHasObject(int index) {
    return hasObject_.getBoolean(index);
  }
  private int hasObjectMemoizedSerializedSize = -1;

  public static final int SIZE_FIELD_NUMBER = 2;
  private int size_ = 0;
  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getHasObjectList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(hasObjectMemoizedSerializedSize);
    }
    for (int i = 0; i < hasObject_.size(); i++) {
      output.writeBoolNoTag(hasObject_.getBoolean(i));
    }
    if (size_ != 0) {
      output.writeInt32(2, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, type_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 1 * getHasObjectList().size();
      size += dataSize;
      if (!getHasObjectList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      hasObjectMemoizedSerializedSize = dataSize;
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, type_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.captchasonic.v1.SingleSolution)) {
      return super.equals(obj);
    }
    com.captchasonic.v1.SingleSolution other = (com.captchasonic.v1.SingleSolution) obj;

    if (!getHasObjectList()
        .equals(other.getHasObjectList())) return false;
    if (getSize()
        != other.getSize()) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHasObjectCount() > 0) {
      hash = (37 * hash) + HAS_OBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getHasObjectList().hashCode();
    }
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.captchasonic.v1.SingleSolution parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.captchasonic.v1.SingleSolution parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.captchasonic.v1.SingleSolution parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.SingleSolution parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.captchasonic.v1.SingleSolution prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code captchasonic.v1.SingleSolution}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:captchasonic.v1.SingleSolution)
      com.captchasonic.v1.SingleSolutionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SingleSolution_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SingleSolution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.captchasonic.v1.SingleSolution.class, com.captchasonic.v1.SingleSolution.Builder.class);
    }

    // Construct using com.captchasonic.v1.SingleSolution.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hasObject_ = emptyBooleanList();
      size_ = 0;
      type_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SingleSolution_descriptor;
    }

    @java.lang.Override
    public com.captchasonic.v1.SingleSolution getDefaultInstanceForType() {
      return com.captchasonic.v1.SingleSolution.getDefaultInstance();
    }

    @java.lang.Override
    public com.captchasonic.v1.SingleSolution build() {
      com.captchasonic.v1.SingleSolution result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.captchasonic.v1.SingleSolution buildPartial() {
      com.captchasonic.v1.SingleSolution result = new com.captchasonic.v1.SingleSolution(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.captchasonic.v1.SingleSolution result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        hasObject_.makeImmutable();
        result.hasObject_ = hasObject_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.type_ = type_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.captchasonic.v1.SingleSolution) {
        return mergeFrom((com.captchasonic.v1.SingleSolution)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.captchasonic.v1.SingleSolution other) {
      if (other == com.captchasonic.v1.SingleSolution.getDefaultInstance()) return this;
      if (!other.hasObject_.isEmpty()) {
        if (hasObject_.isEmpty()) {
          hasObject_ = other.hasObject_;
          hasObject_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureHasObjectIsMutable();
          hasObject_.addAll(other.hasObject_);
        }
        onChanged();
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              boolean v = input.readBool();
              ensureHasObjectIsMutable();
              hasObject_.addBoolean(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureHasObjectIsMutable(alloc / 1);
              while (input.getBytesUntilLimit() > 0) {
                hasObject_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              size_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.BooleanList hasObject_ = emptyBooleanList();
    private void ensureHasObjectIsMutable() {
      if (!hasObject_.isModifiable()) {
        hasObject_ = makeMutableCopy(hasObject_);
      }
      bitField0_ |= 0x00000001;
    }
    private void ensureHasObjectIsMutable(int capacity) {
      if (!hasObject_.isModifiable()) {
        hasObject_ = makeMutableCopy(hasObject_, capacity);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated bool has_object = 1;</code>
     * @return A list containing the hasObject.
     */
    public java.util.List<java.lang.Boolean>
        getHasObjectList() {
      hasObject_.makeImmutable();
      return hasObject_;
    }
    /**
     * <code>repeated bool has_object = 1;</code>
     * @return The count of hasObject.
     */
    public int getHasObjectCount() {
      return hasObject_.size();
    }
    /**
     * <code>repeated bool has_object = 1;</code>
     * @param index The index of the element to return.
     * @return The hasObject at the given index.
     */
    public boolean getHasObject(int index) {
      return hasObject_.getBoolean(index);
    }
    /**
     * <code>repeated bool has_object = 1;</code>
     * @param index The index to set the value at.
     * @param value The hasObject to set.
     * @return This builder for chaining.
     */
    public Builder setHasObject(
        int index, boolean value) {

      ensureHasObjectIsMutable();
      hasObject_.setBoolean(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool has_object = 1;</code>
     * @param value The hasObject to add.
     * @return This builder for chaining.
     */
    public Builder addHasObject(boolean value) {

      ensureHasObjectIsMutable();
      hasObject_.addBoolean(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool has_object = 1;</code>
     * @param values The hasObject to add.
     * @return This builder for chaining.
     */
    public Builder addAllHasObject(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureHasObjectIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hasObject_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool has_object = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasObject() {
      hasObject_ = emptyBooleanList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 2;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 2;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {

      size_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      size_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:captchasonic.v1.SingleSolution)
  }

  // @@protoc_insertion_point(class_scope:captchasonic.v1.SingleSolution)
  private static final com.captchasonic.v1.SingleSolution DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.captchasonic.v1.SingleSolution();
  }

  public static com.captchasonic.v1.SingleSolution getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SingleSolution>
      PARSER = new com.google.protobuf.AbstractParser<SingleSolution>() {
    @java.lang.Override
    public SingleSolution parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SingleSolution> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SingleSolution> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.captchasonic.v1.SingleSolution getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

