// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface SingleSolutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.SingleSolution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bool has_object = 1;</code>
   * @return A list containing the hasObject.
   */
  java.util.List<java.lang.Boolean> getHasObjectList();
  /**
   * <code>repeated bool has_object = 1;</code>
   * @return The count of hasObject.
   */
  int getHasObjectCount();
  /**
   * <code>repeated bool has_object = 1;</code>
   * @param index The index of the element to return.
   * @return The hasObject at the given index.
   */
  boolean getHasObject(int index);

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
