// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface SlideSolutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.SlideSolution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>string raw_json = 2;</code>
   * @return The rawJson.
   */
  java.lang.String getRawJson();
  /**
   * <code>string raw_json = 2;</code>
   * @return The bytes for rawJson.
   */
  com.google.protobuf.ByteString
      getRawJsonBytes();
}
