// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

/**
 * Protobuf type {@code captchasonic.v1.SolutionPayload}
 */
@com.google.protobuf.Generated
public final class SolutionPayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:captchasonic.v1.SolutionPayload)
    SolutionPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "SolutionPayload");
  }
  // Use SolutionPayload.newBuilder() to construct.
  private SolutionPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SolutionPayload() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SolutionPayload_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SolutionPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SolutionPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.captchasonic.v1.SolutionPayload.class, com.captchasonic.v1.SolutionPayload.Builder.class);
  }

  private int kindCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    GRID(1),
    SINGLE(2),
    CLICK(3),
    SLIDE(4),
    TEXT(5),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return GRID;
        case 2: return SINGLE;
        case 3: return CLICK;
        case 4: return SLIDE;
        case 5: return TEXT;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int GRID_FIELD_NUMBER = 1;
  /**
   * <code>.captchasonic.v1.GridSolution grid = 1;</code>
   * @return Whether the grid field is set.
   */
  @java.lang.Override
  public boolean hasGrid() {
    return kindCase_ == 1;
  }
  /**
   * <code>.captchasonic.v1.GridSolution grid = 1;</code>
   * @return The grid.
   */
  @java.lang.Override
  public com.captchasonic.v1.GridSolution getGrid() {
    if (kindCase_ == 1) {
       return (com.captchasonic.v1.GridSolution) kind_;
    }
    return com.captchasonic.v1.GridSolution.getDefaultInstance();
  }
  /**
   * <code>.captchasonic.v1.GridSolution grid = 1;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.GridSolutionOrBuilder getGridOrBuilder() {
    if (kindCase_ == 1) {
       return (com.captchasonic.v1.GridSolution) kind_;
    }
    return com.captchasonic.v1.GridSolution.getDefaultInstance();
  }

  public static final int SINGLE_FIELD_NUMBER = 2;
  /**
   * <code>.captchasonic.v1.SingleSolution single = 2;</code>
   * @return Whether the single field is set.
   */
  @java.lang.Override
  public boolean hasSingle() {
    return kindCase_ == 2;
  }
  /**
   * <code>.captchasonic.v1.SingleSolution single = 2;</code>
   * @return The single.
   */
  @java.lang.Override
  public com.captchasonic.v1.SingleSolution getSingle() {
    if (kindCase_ == 2) {
       return (com.captchasonic.v1.SingleSolution) kind_;
    }
    return com.captchasonic.v1.SingleSolution.getDefaultInstance();
  }
  /**
   * <code>.captchasonic.v1.SingleSolution single = 2;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.SingleSolutionOrBuilder getSingleOrBuilder() {
    if (kindCase_ == 2) {
       return (com.captchasonic.v1.SingleSolution) kind_;
    }
    return com.captchasonic.v1.SingleSolution.getDefaultInstance();
  }

  public static final int CLICK_FIELD_NUMBER = 3;
  /**
   * <code>.captchasonic.v1.ClickSolution click = 3;</code>
   * @return Whether the click field is set.
   */
  @java.lang.Override
  public boolean hasClick() {
    return kindCase_ == 3;
  }
  /**
   * <code>.captchasonic.v1.ClickSolution click = 3;</code>
   * @return The click.
   */
  @java.lang.Override
  public com.captchasonic.v1.ClickSolution getClick() {
    if (kindCase_ == 3) {
       return (com.captchasonic.v1.ClickSolution) kind_;
    }
    return com.captchasonic.v1.ClickSolution.getDefaultInstance();
  }
  /**
   * <code>.captchasonic.v1.ClickSolution click = 3;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.ClickSolutionOrBuilder getClickOrBuilder() {
    if (kindCase_ == 3) {
       return (com.captchasonic.v1.ClickSolution) kind_;
    }
    return com.captchasonic.v1.ClickSolution.getDefaultInstance();
  }

  public static final int SLIDE_FIELD_NUMBER = 4;
  /**
   * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
   * @return Whether the slide field is set.
   */
  @java.lang.Override
  public boolean hasSlide() {
    return kindCase_ == 4;
  }
  /**
   * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
   * @return The slide.
   */
  @java.lang.Override
  public com.captchasonic.v1.SlideSolution getSlide() {
    if (kindCase_ == 4) {
       return (com.captchasonic.v1.SlideSolution) kind_;
    }
    return com.captchasonic.v1.SlideSolution.getDefaultInstance();
  }
  /**
   * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.SlideSolutionOrBuilder getSlideOrBuilder() {
    if (kindCase_ == 4) {
       return (com.captchasonic.v1.SlideSolution) kind_;
    }
    return com.captchasonic.v1.SlideSolution.getDefaultInstance();
  }

  public static final int TEXT_FIELD_NUMBER = 5;
  /**
   * <code>.captchasonic.v1.TextSolution text = 5;</code>
   * @return Whether the text field is set.
   */
  @java.lang.Override
  public boolean hasText() {
    return kindCase_ == 5;
  }
  /**
   * <code>.captchasonic.v1.TextSolution text = 5;</code>
   * @return The text.
   */
  @java.lang.Override
  public com.captchasonic.v1.TextSolution getText() {
    if (kindCase_ == 5) {
       return (com.captchasonic.v1.TextSolution) kind_;
    }
    return com.captchasonic.v1.TextSolution.getDefaultInstance();
  }
  /**
   * <code>.captchasonic.v1.TextSolution text = 5;</code>
   */
  @java.lang.Override
  public com.captchasonic.v1.TextSolutionOrBuilder getTextOrBuilder() {
    if (kindCase_ == 5) {
       return (com.captchasonic.v1.TextSolution) kind_;
    }
    return com.captchasonic.v1.TextSolution.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeMessage(1, (com.captchasonic.v1.GridSolution) kind_);
    }
    if (kindCase_ == 2) {
      output.writeMessage(2, (com.captchasonic.v1.SingleSolution) kind_);
    }
    if (kindCase_ == 3) {
      output.writeMessage(3, (com.captchasonic.v1.ClickSolution) kind_);
    }
    if (kindCase_ == 4) {
      output.writeMessage(4, (com.captchasonic.v1.SlideSolution) kind_);
    }
    if (kindCase_ == 5) {
      output.writeMessage(5, (com.captchasonic.v1.TextSolution) kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.captchasonic.v1.GridSolution) kind_);
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.captchasonic.v1.SingleSolution) kind_);
    }
    if (kindCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.captchasonic.v1.ClickSolution) kind_);
    }
    if (kindCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.captchasonic.v1.SlideSolution) kind_);
    }
    if (kindCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.captchasonic.v1.TextSolution) kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.captchasonic.v1.SolutionPayload)) {
      return super.equals(obj);
    }
    com.captchasonic.v1.SolutionPayload other = (com.captchasonic.v1.SolutionPayload) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (!getGrid()
            .equals(other.getGrid())) return false;
        break;
      case 2:
        if (!getSingle()
            .equals(other.getSingle())) return false;
        break;
      case 3:
        if (!getClick()
            .equals(other.getClick())) return false;
        break;
      case 4:
        if (!getSlide()
            .equals(other.getSlide())) return false;
        break;
      case 5:
        if (!getText()
            .equals(other.getText())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + GRID_FIELD_NUMBER;
        hash = (53 * hash) + getGrid().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SINGLE_FIELD_NUMBER;
        hash = (53 * hash) + getSingle().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CLICK_FIELD_NUMBER;
        hash = (53 * hash) + getClick().hashCode();
        break;
      case 4:
        hash = (37 * hash) + SLIDE_FIELD_NUMBER;
        hash = (53 * hash) + getSlide().hashCode();
        break;
      case 5:
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.captchasonic.v1.SolutionPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.captchasonic.v1.SolutionPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.captchasonic.v1.SolutionPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.SolutionPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.captchasonic.v1.SolutionPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code captchasonic.v1.SolutionPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:captchasonic.v1.SolutionPayload)
      com.captchasonic.v1.SolutionPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SolutionPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SolutionPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.captchasonic.v1.SolutionPayload.class, com.captchasonic.v1.SolutionPayload.Builder.class);
    }

    // Construct using com.captchasonic.v1.SolutionPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (gridBuilder_ != null) {
        gridBuilder_.clear();
      }
      if (singleBuilder_ != null) {
        singleBuilder_.clear();
      }
      if (clickBuilder_ != null) {
        clickBuilder_.clear();
      }
      if (slideBuilder_ != null) {
        slideBuilder_.clear();
      }
      if (textBuilder_ != null) {
        textBuilder_.clear();
      }
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_SolutionPayload_descriptor;
    }

    @java.lang.Override
    public com.captchasonic.v1.SolutionPayload getDefaultInstanceForType() {
      return com.captchasonic.v1.SolutionPayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.captchasonic.v1.SolutionPayload build() {
      com.captchasonic.v1.SolutionPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.captchasonic.v1.SolutionPayload buildPartial() {
      com.captchasonic.v1.SolutionPayload result = new com.captchasonic.v1.SolutionPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.captchasonic.v1.SolutionPayload result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.captchasonic.v1.SolutionPayload result) {
      result.kindCase_ = kindCase_;
      result.kind_ = this.kind_;
      if (kindCase_ == 1 &&
          gridBuilder_ != null) {
        result.kind_ = gridBuilder_.build();
      }
      if (kindCase_ == 2 &&
          singleBuilder_ != null) {
        result.kind_ = singleBuilder_.build();
      }
      if (kindCase_ == 3 &&
          clickBuilder_ != null) {
        result.kind_ = clickBuilder_.build();
      }
      if (kindCase_ == 4 &&
          slideBuilder_ != null) {
        result.kind_ = slideBuilder_.build();
      }
      if (kindCase_ == 5 &&
          textBuilder_ != null) {
        result.kind_ = textBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.captchasonic.v1.SolutionPayload) {
        return mergeFrom((com.captchasonic.v1.SolutionPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.captchasonic.v1.SolutionPayload other) {
      if (other == com.captchasonic.v1.SolutionPayload.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case GRID: {
          mergeGrid(other.getGrid());
          break;
        }
        case SINGLE: {
          mergeSingle(other.getSingle());
          break;
        }
        case CLICK: {
          mergeClick(other.getClick());
          break;
        }
        case SLIDE: {
          mergeSlide(other.getSlide());
          break;
        }
        case TEXT: {
          mergeText(other.getText());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetGridFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetSingleFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetClickFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetSlideFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.GridSolution, com.captchasonic.v1.GridSolution.Builder, com.captchasonic.v1.GridSolutionOrBuilder> gridBuilder_;
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     * @return Whether the grid field is set.
     */
    @java.lang.Override
    public boolean hasGrid() {
      return kindCase_ == 1;
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     * @return The grid.
     */
    @java.lang.Override
    public com.captchasonic.v1.GridSolution getGrid() {
      if (gridBuilder_ == null) {
        if (kindCase_ == 1) {
          return (com.captchasonic.v1.GridSolution) kind_;
        }
        return com.captchasonic.v1.GridSolution.getDefaultInstance();
      } else {
        if (kindCase_ == 1) {
          return gridBuilder_.getMessage();
        }
        return com.captchasonic.v1.GridSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     */
    public Builder setGrid(com.captchasonic.v1.GridSolution value) {
      if (gridBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        gridBuilder_.setMessage(value);
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     */
    public Builder setGrid(
        com.captchasonic.v1.GridSolution.Builder builderForValue) {
      if (gridBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        gridBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     */
    public Builder mergeGrid(com.captchasonic.v1.GridSolution value) {
      if (gridBuilder_ == null) {
        if (kindCase_ == 1 &&
            kind_ != com.captchasonic.v1.GridSolution.getDefaultInstance()) {
          kind_ = com.captchasonic.v1.GridSolution.newBuilder((com.captchasonic.v1.GridSolution) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 1) {
          gridBuilder_.mergeFrom(value);
        } else {
          gridBuilder_.setMessage(value);
        }
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     */
    public Builder clearGrid() {
      if (gridBuilder_ == null) {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
        }
        gridBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     */
    public com.captchasonic.v1.GridSolution.Builder getGridBuilder() {
      return internalGetGridFieldBuilder().getBuilder();
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     */
    @java.lang.Override
    public com.captchasonic.v1.GridSolutionOrBuilder getGridOrBuilder() {
      if ((kindCase_ == 1) && (gridBuilder_ != null)) {
        return gridBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 1) {
          return (com.captchasonic.v1.GridSolution) kind_;
        }
        return com.captchasonic.v1.GridSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.GridSolution grid = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.GridSolution, com.captchasonic.v1.GridSolution.Builder, com.captchasonic.v1.GridSolutionOrBuilder> 
        internalGetGridFieldBuilder() {
      if (gridBuilder_ == null) {
        if (!(kindCase_ == 1)) {
          kind_ = com.captchasonic.v1.GridSolution.getDefaultInstance();
        }
        gridBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.GridSolution, com.captchasonic.v1.GridSolution.Builder, com.captchasonic.v1.GridSolutionOrBuilder>(
                (com.captchasonic.v1.GridSolution) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 1;
      onChanged();
      return gridBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.SingleSolution, com.captchasonic.v1.SingleSolution.Builder, com.captchasonic.v1.SingleSolutionOrBuilder> singleBuilder_;
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     * @return Whether the single field is set.
     */
    @java.lang.Override
    public boolean hasSingle() {
      return kindCase_ == 2;
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     * @return The single.
     */
    @java.lang.Override
    public com.captchasonic.v1.SingleSolution getSingle() {
      if (singleBuilder_ == null) {
        if (kindCase_ == 2) {
          return (com.captchasonic.v1.SingleSolution) kind_;
        }
        return com.captchasonic.v1.SingleSolution.getDefaultInstance();
      } else {
        if (kindCase_ == 2) {
          return singleBuilder_.getMessage();
        }
        return com.captchasonic.v1.SingleSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     */
    public Builder setSingle(com.captchasonic.v1.SingleSolution value) {
      if (singleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        singleBuilder_.setMessage(value);
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     */
    public Builder setSingle(
        com.captchasonic.v1.SingleSolution.Builder builderForValue) {
      if (singleBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        singleBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     */
    public Builder mergeSingle(com.captchasonic.v1.SingleSolution value) {
      if (singleBuilder_ == null) {
        if (kindCase_ == 2 &&
            kind_ != com.captchasonic.v1.SingleSolution.getDefaultInstance()) {
          kind_ = com.captchasonic.v1.SingleSolution.newBuilder((com.captchasonic.v1.SingleSolution) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 2) {
          singleBuilder_.mergeFrom(value);
        } else {
          singleBuilder_.setMessage(value);
        }
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     */
    public Builder clearSingle() {
      if (singleBuilder_ == null) {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
        }
        singleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     */
    public com.captchasonic.v1.SingleSolution.Builder getSingleBuilder() {
      return internalGetSingleFieldBuilder().getBuilder();
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     */
    @java.lang.Override
    public com.captchasonic.v1.SingleSolutionOrBuilder getSingleOrBuilder() {
      if ((kindCase_ == 2) && (singleBuilder_ != null)) {
        return singleBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 2) {
          return (com.captchasonic.v1.SingleSolution) kind_;
        }
        return com.captchasonic.v1.SingleSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.SingleSolution single = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.SingleSolution, com.captchasonic.v1.SingleSolution.Builder, com.captchasonic.v1.SingleSolutionOrBuilder> 
        internalGetSingleFieldBuilder() {
      if (singleBuilder_ == null) {
        if (!(kindCase_ == 2)) {
          kind_ = com.captchasonic.v1.SingleSolution.getDefaultInstance();
        }
        singleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.SingleSolution, com.captchasonic.v1.SingleSolution.Builder, com.captchasonic.v1.SingleSolutionOrBuilder>(
                (com.captchasonic.v1.SingleSolution) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 2;
      onChanged();
      return singleBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.ClickSolution, com.captchasonic.v1.ClickSolution.Builder, com.captchasonic.v1.ClickSolutionOrBuilder> clickBuilder_;
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     * @return Whether the click field is set.
     */
    @java.lang.Override
    public boolean hasClick() {
      return kindCase_ == 3;
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     * @return The click.
     */
    @java.lang.Override
    public com.captchasonic.v1.ClickSolution getClick() {
      if (clickBuilder_ == null) {
        if (kindCase_ == 3) {
          return (com.captchasonic.v1.ClickSolution) kind_;
        }
        return com.captchasonic.v1.ClickSolution.getDefaultInstance();
      } else {
        if (kindCase_ == 3) {
          return clickBuilder_.getMessage();
        }
        return com.captchasonic.v1.ClickSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     */
    public Builder setClick(com.captchasonic.v1.ClickSolution value) {
      if (clickBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        clickBuilder_.setMessage(value);
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     */
    public Builder setClick(
        com.captchasonic.v1.ClickSolution.Builder builderForValue) {
      if (clickBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        clickBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     */
    public Builder mergeClick(com.captchasonic.v1.ClickSolution value) {
      if (clickBuilder_ == null) {
        if (kindCase_ == 3 &&
            kind_ != com.captchasonic.v1.ClickSolution.getDefaultInstance()) {
          kind_ = com.captchasonic.v1.ClickSolution.newBuilder((com.captchasonic.v1.ClickSolution) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 3) {
          clickBuilder_.mergeFrom(value);
        } else {
          clickBuilder_.setMessage(value);
        }
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     */
    public Builder clearClick() {
      if (clickBuilder_ == null) {
        if (kindCase_ == 3) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 3) {
          kindCase_ = 0;
          kind_ = null;
        }
        clickBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     */
    public com.captchasonic.v1.ClickSolution.Builder getClickBuilder() {
      return internalGetClickFieldBuilder().getBuilder();
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     */
    @java.lang.Override
    public com.captchasonic.v1.ClickSolutionOrBuilder getClickOrBuilder() {
      if ((kindCase_ == 3) && (clickBuilder_ != null)) {
        return clickBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 3) {
          return (com.captchasonic.v1.ClickSolution) kind_;
        }
        return com.captchasonic.v1.ClickSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.ClickSolution click = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.ClickSolution, com.captchasonic.v1.ClickSolution.Builder, com.captchasonic.v1.ClickSolutionOrBuilder> 
        internalGetClickFieldBuilder() {
      if (clickBuilder_ == null) {
        if (!(kindCase_ == 3)) {
          kind_ = com.captchasonic.v1.ClickSolution.getDefaultInstance();
        }
        clickBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.ClickSolution, com.captchasonic.v1.ClickSolution.Builder, com.captchasonic.v1.ClickSolutionOrBuilder>(
                (com.captchasonic.v1.ClickSolution) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 3;
      onChanged();
      return clickBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.SlideSolution, com.captchasonic.v1.SlideSolution.Builder, com.captchasonic.v1.SlideSolutionOrBuilder> slideBuilder_;
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     * @return Whether the slide field is set.
     */
    @java.lang.Override
    public boolean hasSlide() {
      return kindCase_ == 4;
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     * @return The slide.
     */
    @java.lang.Override
    public com.captchasonic.v1.SlideSolution getSlide() {
      if (slideBuilder_ == null) {
        if (kindCase_ == 4) {
          return (com.captchasonic.v1.SlideSolution) kind_;
        }
        return com.captchasonic.v1.SlideSolution.getDefaultInstance();
      } else {
        if (kindCase_ == 4) {
          return slideBuilder_.getMessage();
        }
        return com.captchasonic.v1.SlideSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     */
    public Builder setSlide(com.captchasonic.v1.SlideSolution value) {
      if (slideBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        slideBuilder_.setMessage(value);
      }
      kindCase_ = 4;
      return this;
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     */
    public Builder setSlide(
        com.captchasonic.v1.SlideSolution.Builder builderForValue) {
      if (slideBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        slideBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 4;
      return this;
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     */
    public Builder mergeSlide(com.captchasonic.v1.SlideSolution value) {
      if (slideBuilder_ == null) {
        if (kindCase_ == 4 &&
            kind_ != com.captchasonic.v1.SlideSolution.getDefaultInstance()) {
          kind_ = com.captchasonic.v1.SlideSolution.newBuilder((com.captchasonic.v1.SlideSolution) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 4) {
          slideBuilder_.mergeFrom(value);
        } else {
          slideBuilder_.setMessage(value);
        }
      }
      kindCase_ = 4;
      return this;
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     */
    public Builder clearSlide() {
      if (slideBuilder_ == null) {
        if (kindCase_ == 4) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 4) {
          kindCase_ = 0;
          kind_ = null;
        }
        slideBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     */
    public com.captchasonic.v1.SlideSolution.Builder getSlideBuilder() {
      return internalGetSlideFieldBuilder().getBuilder();
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     */
    @java.lang.Override
    public com.captchasonic.v1.SlideSolutionOrBuilder getSlideOrBuilder() {
      if ((kindCase_ == 4) && (slideBuilder_ != null)) {
        return slideBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 4) {
          return (com.captchasonic.v1.SlideSolution) kind_;
        }
        return com.captchasonic.v1.SlideSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.SlideSolution, com.captchasonic.v1.SlideSolution.Builder, com.captchasonic.v1.SlideSolutionOrBuilder> 
        internalGetSlideFieldBuilder() {
      if (slideBuilder_ == null) {
        if (!(kindCase_ == 4)) {
          kind_ = com.captchasonic.v1.SlideSolution.getDefaultInstance();
        }
        slideBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.SlideSolution, com.captchasonic.v1.SlideSolution.Builder, com.captchasonic.v1.SlideSolutionOrBuilder>(
                (com.captchasonic.v1.SlideSolution) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 4;
      onChanged();
      return slideBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.TextSolution, com.captchasonic.v1.TextSolution.Builder, com.captchasonic.v1.TextSolutionOrBuilder> textBuilder_;
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return kindCase_ == 5;
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     * @return The text.
     */
    @java.lang.Override
    public com.captchasonic.v1.TextSolution getText() {
      if (textBuilder_ == null) {
        if (kindCase_ == 5) {
          return (com.captchasonic.v1.TextSolution) kind_;
        }
        return com.captchasonic.v1.TextSolution.getDefaultInstance();
      } else {
        if (kindCase_ == 5) {
          return textBuilder_.getMessage();
        }
        return com.captchasonic.v1.TextSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     */
    public Builder setText(com.captchasonic.v1.TextSolution value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        textBuilder_.setMessage(value);
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     */
    public Builder setText(
        com.captchasonic.v1.TextSolution.Builder builderForValue) {
      if (textBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        textBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     */
    public Builder mergeText(com.captchasonic.v1.TextSolution value) {
      if (textBuilder_ == null) {
        if (kindCase_ == 5 &&
            kind_ != com.captchasonic.v1.TextSolution.getDefaultInstance()) {
          kind_ = com.captchasonic.v1.TextSolution.newBuilder((com.captchasonic.v1.TextSolution) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 5) {
          textBuilder_.mergeFrom(value);
        } else {
          textBuilder_.setMessage(value);
        }
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     */
    public Builder clearText() {
      if (textBuilder_ == null) {
        if (kindCase_ == 5) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 5) {
          kindCase_ = 0;
          kind_ = null;
        }
        textBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     */
    public com.captchasonic.v1.TextSolution.Builder getTextBuilder() {
      return internalGetTextFieldBuilder().getBuilder();
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     */
    @java.lang.Override
    public com.captchasonic.v1.TextSolutionOrBuilder getTextOrBuilder() {
      if ((kindCase_ == 5) && (textBuilder_ != null)) {
        return textBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 5) {
          return (com.captchasonic.v1.TextSolution) kind_;
        }
        return com.captchasonic.v1.TextSolution.getDefaultInstance();
      }
    }
    /**
     * <code>.captchasonic.v1.TextSolution text = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.captchasonic.v1.TextSolution, com.captchasonic.v1.TextSolution.Builder, com.captchasonic.v1.TextSolutionOrBuilder> 
        internalGetTextFieldBuilder() {
      if (textBuilder_ == null) {
        if (!(kindCase_ == 5)) {
          kind_ = com.captchasonic.v1.TextSolution.getDefaultInstance();
        }
        textBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.captchasonic.v1.TextSolution, com.captchasonic.v1.TextSolution.Builder, com.captchasonic.v1.TextSolutionOrBuilder>(
                (com.captchasonic.v1.TextSolution) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 5;
      onChanged();
      return textBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:captchasonic.v1.SolutionPayload)
  }

  // @@protoc_insertion_point(class_scope:captchasonic.v1.SolutionPayload)
  private static final com.captchasonic.v1.SolutionPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.captchasonic.v1.SolutionPayload();
  }

  public static com.captchasonic.v1.SolutionPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SolutionPayload>
      PARSER = new com.google.protobuf.AbstractParser<SolutionPayload>() {
    @java.lang.Override
    public SolutionPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SolutionPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SolutionPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.captchasonic.v1.SolutionPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

