// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface SolutionPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.SolutionPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.captchasonic.v1.GridSolution grid = 1;</code>
   * @return Whether the grid field is set.
   */
  boolean hasGrid();
  /**
   * <code>.captchasonic.v1.GridSolution grid = 1;</code>
   * @return The grid.
   */
  com.captchasonic.v1.GridSolution getGrid();
  /**
   * <code>.captchasonic.v1.GridSolution grid = 1;</code>
   */
  com.captchasonic.v1.GridSolutionOrBuilder getGridOrBuilder();

  /**
   * <code>.captchasonic.v1.SingleSolution single = 2;</code>
   * @return Whether the single field is set.
   */
  boolean hasSingle();
  /**
   * <code>.captchasonic.v1.SingleSolution single = 2;</code>
   * @return The single.
   */
  com.captchasonic.v1.SingleSolution getSingle();
  /**
   * <code>.captchasonic.v1.SingleSolution single = 2;</code>
   */
  com.captchasonic.v1.SingleSolutionOrBuilder getSingleOrBuilder();

  /**
   * <code>.captchasonic.v1.ClickSolution click = 3;</code>
   * @return Whether the click field is set.
   */
  boolean hasClick();
  /**
   * <code>.captchasonic.v1.ClickSolution click = 3;</code>
   * @return The click.
   */
  com.captchasonic.v1.ClickSolution getClick();
  /**
   * <code>.captchasonic.v1.ClickSolution click = 3;</code>
   */
  com.captchasonic.v1.ClickSolutionOrBuilder getClickOrBuilder();

  /**
   * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
   * @return Whether the slide field is set.
   */
  boolean hasSlide();
  /**
   * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
   * @return The slide.
   */
  com.captchasonic.v1.SlideSolution getSlide();
  /**
   * <code>.captchasonic.v1.SlideSolution slide = 4;</code>
   */
  com.captchasonic.v1.SlideSolutionOrBuilder getSlideOrBuilder();

  /**
   * <code>.captchasonic.v1.TextSolution text = 5;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>.captchasonic.v1.TextSolution text = 5;</code>
   * @return The text.
   */
  com.captchasonic.v1.TextSolution getText();
  /**
   * <code>.captchasonic.v1.TextSolution text = 5;</code>
   */
  com.captchasonic.v1.TextSolutionOrBuilder getTextOrBuilder();

  com.captchasonic.v1.SolutionPayload.KindCase getKindCase();
}
