// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public final class SonicProtos extends com.google.protobuf.GeneratedFile {
  private SonicProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "SonicProtos");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_CreateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_CreateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_CreateTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_CreateTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_CreateTaskResponse_SolutionEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_CreateTaskResponse_SolutionEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_VideoCanvasParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_VideoCanvasParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_SolutionPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_SolutionPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_GridSolution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_GridSolution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_SingleSolution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_SingleSolution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_ClickCoord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_ClickCoord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_ClickGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_ClickGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_ClickSolution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_ClickSolution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_SlideSolution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_SlideSolution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_TextSolution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_TextSolution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_GetTaskResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_GetTaskResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_GetTaskResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_GetTaskResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_GetTaskResultResponse_SolutionEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_GetTaskResultResponse_SolutionEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_GetBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_GetBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_GetBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_GetBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_captchasonic_v1_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_captchasonic_v1_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033captchasonic/v1/sonic.proto\022\017captchaso" +
      "nic.v1\"\323\003\n\004Task\022\014\n\004type\030\001 \001(\t\022\016\n\006images\030" +
      "\002 \003(\014\022\020\n\010question\030\003 \001(\t\022\024\n\014questionType\030" +
      "\004 \001(\t\022\022\n\nscreenshot\030\005 \001(\010\022\r\n\005image\030\006 \001(\014" +
      "\022\020\n\010examples\030\007 \003(\014\022\022\n\nwebsiteURL\030\010 \001(\t\022\022" +
      "\n\nwebsiteKey\030\t \001(\t\022\016\n\006module\030\n \001(\t\022\017\n\007nu" +
      "meric\030\013 \001(\010\022\026\n\016case_sensitive\030\014 \001(\010\022\021\n\tm" +
      "inLength\030\r \001(\005\022\021\n\tmaxLength\030\016 \001(\005\022\013\n\003gtv" +
      "\030\017 \001(\005\022\n\n\002gt\030\020 \001(\t\022\021\n\tchallenge\030\021 \001(\t\022\021\n" +
      "\tcaptchaId\030\022 \001(\t\022\r\n\005proxy\030\023 \001(\t\022\023\n\013canva" +
      "sVideo\030\024 \001(\010\022\016\n\006format\030\025 \001(\t\022\r\n\005video\030\026 " +
      "\003(\014\022\016\n\006frames\030\027 \003(\005\022\027\n\nframecount\030\030 \001(\005H" +
      "\000\210\001\001\022\017\n\007choices\030\031 \003(\tB\r\n\013_framecount\"H\n\021" +
      "CreateTaskRequest\022\016\n\006apiKey\030\001 \001(\t\022#\n\004tas" +
      "k\030\002 \001(\0132\025.captchasonic.v1.Task\"\203\004\n\022Creat" +
      "eTaskResponse\022\017\n\007errorId\030\001 \001(\005\022\030\n\020errorD" +
      "escription\030\002 \001(\t\022\016\n\006taskId\030\003 \001(\t\022C\n\010solu" +
      "tion\030\004 \003(\01321.captchasonic.v1.CreateTaskR" +
      "esponse.SolutionEntry\022\016\n\006status\030\005 \001(\t\0228\n" +
      "\016typed_solution\030\006 \001(\0132 .captchasonic.v1." +
      "SolutionPayload\022\014\n\004code\030\007 \001(\005\022\013\n\003msg\030\010 \001" +
      "(\t\022\020\n\010question\030\t \001(\t\022\024\n\014questionType\030\n \001" +
      "(\t\022\027\n\017questionVariant\030\013 \001(\t\022\025\n\rretryAfte" +
      "rSec\030\014 \001(\005\022\r\n\005video\030\r \001(\010\0228\n\014canvasParam" +
      "s\030\016 \001(\0132\".captchasonic.v1.VideoCanvasPar" +
      "ams\022\016\n\006frames\030\017 \003(\005\022\027\n\nframecount\030\020 \001(\005H" +
      "\000\210\001\001\032/\n\rSolutionEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001B\r\n\013_framecount\"|\n\021VideoCan" +
      "vasParams\022\020\n\010duration\030\001 \001(\005\022\016\n\006format\030\002 " +
      "\003(\t\022\016\n\006frames\030\003 \003(\005\022\027\n\nframecount\030\004 \001(\005H" +
      "\000\210\001\001\022\r\n\005video\030\005 \001(\010B\r\n\013_framecount\"\214\002\n\017S" +
      "olutionPayload\022-\n\004grid\030\001 \001(\0132\035.captchaso" +
      "nic.v1.GridSolutionH\000\0221\n\006single\030\002 \001(\0132\037." +
      "captchasonic.v1.SingleSolutionH\000\022/\n\005clic" +
      "k\030\003 \001(\0132\036.captchasonic.v1.ClickSolutionH" +
      "\000\022/\n\005slide\030\004 \001(\0132\036.captchasonic.v1.Slide" +
      "SolutionH\000\022-\n\004text\030\005 \001(\0132\035.captchasonic." +
      "v1.TextSolutionH\000B\006\n\004kind\";\n\014GridSolutio" +
      "n\022\017\n\007objects\030\001 \003(\005\022\014\n\004size\030\002 \001(\005\022\014\n\004type" +
      "\030\003 \001(\t\"@\n\016SingleSolution\022\022\n\nhas_object\030\001" +
      " \003(\010\022\014\n\004size\030\002 \001(\005\022\014\n\004type\030\003 \001(\t\"\"\n\nClic" +
      "kCoord\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\"9\n\nClickGro" +
      "up\022+\n\006coords\030\001 \003(\0132\033.captchasonic.v1.Cli" +
      "ckCoord\"<\n\rClickSolution\022+\n\006groups\030\001 \003(\013" +
      "2\033.captchasonic.v1.ClickGroup\",\n\rSlideSo" +
      "lution\022\t\n\001x\030\001 \001(\005\022\020\n\010raw_json\030\002 \001(\t\"\035\n\014T" +
      "extSolution\022\r\n\005texts\030\001 \003(\t\"6\n\024GetTaskRes" +
      "ultRequest\022\016\n\006apiKey\030\001 \001(\t\022\016\n\006taskId\030\002 \001" +
      "(\t\"\353\001\n\025GetTaskResultResponse\022\017\n\007errorId\030" +
      "\001 \001(\005\022\016\n\006status\030\002 \001(\t\022F\n\010solution\030\003 \003(\0132" +
      "4.captchasonic.v1.GetTaskResultResponse." +
      "SolutionEntry\0228\n\016typed_solution\030\004 \001(\0132 ." +
      "captchasonic.v1.SolutionPayload\032/\n\rSolut" +
      "ionEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "\"#\n\021GetBalanceRequest\022\016\n\006apiKey\030\001 \001(\t\"F\n" +
      "\022GetBalanceResponse\022\017\n\007balance\030\001 \001(\001\022\017\n\007" +
      "errorId\030\002 \001(\005\022\016\n\006status\030\003 \001(\t\"\024\n\022HealthC" +
      "heckRequest\"7\n\023HealthCheckResponse\022\017\n\007he" +
      "althy\030\001 \001(\010\022\017\n\007version\030\002 \001(\t2\373\002\n\014SonicSe" +
      "rvice\022U\n\nCreateTask\022\".captchasonic.v1.Cr" +
      "eateTaskRequest\032#.captchasonic.v1.Create" +
      "TaskResponse\022^\n\rGetTaskResult\022%.captchas" +
      "onic.v1.GetTaskResultRequest\032&.captchaso" +
      "nic.v1.GetTaskResultResponse\022U\n\nGetBalan" +
      "ce\022\".captchasonic.v1.GetBalanceRequest\032#" +
      ".captchasonic.v1.GetBalanceResponse\022]\n\013H" +
      "ealthCheck\022#.captchasonic.v1.HealthCheck" +
      "Request\032$.captchasonic.v1.HealthCheckRes" +
      "ponse\"\003\220\002\001Bz\n\023com.captchasonic.v1B\013Sonic" +
      "ProtosP\001ZBgithub.com/captchasonic/captch" +
      "asonic-go/internal/pb;captchasonicv1\252\002\017C" +
      "aptchaSonic.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_captchasonic_v1_Task_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_captchasonic_v1_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_Task_descriptor,
        new java.lang.String[] { "Type", "Images", "Question", "QuestionType", "Screenshot", "Image", "Examples", "WebsiteURL", "WebsiteKey", "Module", "Numeric", "CaseSensitive", "MinLength", "MaxLength", "Gtv", "Gt", "Challenge", "CaptchaId", "Proxy", "CanvasVideo", "Format", "Video", "Frames", "Framecount", "Choices", });
    internal_static_captchasonic_v1_CreateTaskRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_captchasonic_v1_CreateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_CreateTaskRequest_descriptor,
        new java.lang.String[] { "ApiKey", "Task", });
    internal_static_captchasonic_v1_CreateTaskResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_captchasonic_v1_CreateTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_CreateTaskResponse_descriptor,
        new java.lang.String[] { "ErrorId", "ErrorDescription", "TaskId", "Solution", "Status", "TypedSolution", "Code", "Msg", "Question", "QuestionType", "QuestionVariant", "RetryAfterSec", "Video", "CanvasParams", "Frames", "Framecount", });
    internal_static_captchasonic_v1_CreateTaskResponse_SolutionEntry_descriptor =
      internal_static_captchasonic_v1_CreateTaskResponse_descriptor.getNestedType(0);
    internal_static_captchasonic_v1_CreateTaskResponse_SolutionEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_CreateTaskResponse_SolutionEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_captchasonic_v1_VideoCanvasParams_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_captchasonic_v1_VideoCanvasParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_VideoCanvasParams_descriptor,
        new java.lang.String[] { "Duration", "Format", "Frames", "Framecount", "Video", });
    internal_static_captchasonic_v1_SolutionPayload_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_captchasonic_v1_SolutionPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_SolutionPayload_descriptor,
        new java.lang.String[] { "Grid", "Single", "Click", "Slide", "Text", "Kind", });
    internal_static_captchasonic_v1_GridSolution_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_captchasonic_v1_GridSolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_GridSolution_descriptor,
        new java.lang.String[] { "Objects", "Size", "Type", });
    internal_static_captchasonic_v1_SingleSolution_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_captchasonic_v1_SingleSolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_SingleSolution_descriptor,
        new java.lang.String[] { "HasObject", "Size", "Type", });
    internal_static_captchasonic_v1_ClickCoord_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_captchasonic_v1_ClickCoord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_ClickCoord_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_captchasonic_v1_ClickGroup_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_captchasonic_v1_ClickGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_ClickGroup_descriptor,
        new java.lang.String[] { "Coords", });
    internal_static_captchasonic_v1_ClickSolution_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_captchasonic_v1_ClickSolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_ClickSolution_descriptor,
        new java.lang.String[] { "Groups", });
    internal_static_captchasonic_v1_SlideSolution_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_captchasonic_v1_SlideSolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_SlideSolution_descriptor,
        new java.lang.String[] { "X", "RawJson", });
    internal_static_captchasonic_v1_TextSolution_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_captchasonic_v1_TextSolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_TextSolution_descriptor,
        new java.lang.String[] { "Texts", });
    internal_static_captchasonic_v1_GetTaskResultRequest_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_captchasonic_v1_GetTaskResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_GetTaskResultRequest_descriptor,
        new java.lang.String[] { "ApiKey", "TaskId", });
    internal_static_captchasonic_v1_GetTaskResultResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_captchasonic_v1_GetTaskResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_GetTaskResultResponse_descriptor,
        new java.lang.String[] { "ErrorId", "Status", "Solution", "TypedSolution", });
    internal_static_captchasonic_v1_GetTaskResultResponse_SolutionEntry_descriptor =
      internal_static_captchasonic_v1_GetTaskResultResponse_descriptor.getNestedType(0);
    internal_static_captchasonic_v1_GetTaskResultResponse_SolutionEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_GetTaskResultResponse_SolutionEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_captchasonic_v1_GetBalanceRequest_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_captchasonic_v1_GetBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_GetBalanceRequest_descriptor,
        new java.lang.String[] { "ApiKey", });
    internal_static_captchasonic_v1_GetBalanceResponse_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_captchasonic_v1_GetBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_GetBalanceResponse_descriptor,
        new java.lang.String[] { "Balance", "ErrorId", "Status", });
    internal_static_captchasonic_v1_HealthCheckRequest_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_captchasonic_v1_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_captchasonic_v1_HealthCheckResponse_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_captchasonic_v1_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_captchasonic_v1_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Healthy", "Version", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
