// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface TaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.Task)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * raw binary — no base64 overhead
   * </pre>
   *
   * <code>repeated bytes images = 2;</code>
   * @return A list containing the images.
   */
  java.util.List<com.google.protobuf.ByteString> getImagesList();
  /**
   * <pre>
   * raw binary — no base64 overhead
   * </pre>
   *
   * <code>repeated bytes images = 2;</code>
   * @return The count of images.
   */
  int getImagesCount();
  /**
   * <pre>
   * raw binary — no base64 overhead
   * </pre>
   *
   * <code>repeated bytes images = 2;</code>
   * @param index The index of the element to return.
   * @return The images at the given index.
   */
  com.google.protobuf.ByteString getImages(int index);

  /**
   * <code>string question = 3;</code>
   * @return The question.
   */
  java.lang.String getQuestion();
  /**
   * <code>string question = 3;</code>
   * @return The bytes for question.
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <code>string questionType = 4;</code>
   * @return The questionType.
   */
  java.lang.String getQuestionType();
  /**
   * <code>string questionType = 4;</code>
   * @return The bytes for questionType.
   */
  com.google.protobuf.ByteString
      getQuestionTypeBytes();

  /**
   * <code>bool screenshot = 5;</code>
   * @return The screenshot.
   */
  boolean getScreenshot();

  /**
   * <code>bytes image = 6;</code>
   * @return The image.
   */
  com.google.protobuf.ByteString getImage();

  /**
   * <code>repeated bytes examples = 7;</code>
   * @return A list containing the examples.
   */
  java.util.List<com.google.protobuf.ByteString> getExamplesList();
  /**
   * <code>repeated bytes examples = 7;</code>
   * @return The count of examples.
   */
  int getExamplesCount();
  /**
   * <code>repeated bytes examples = 7;</code>
   * @param index The index of the element to return.
   * @return The examples at the given index.
   */
  com.google.protobuf.ByteString getExamples(int index);

  /**
   * <code>string websiteURL = 8;</code>
   * @return The websiteURL.
   */
  java.lang.String getWebsiteURL();
  /**
   * <code>string websiteURL = 8;</code>
   * @return The bytes for websiteURL.
   */
  com.google.protobuf.ByteString
      getWebsiteURLBytes();

  /**
   * <code>string websiteKey = 9;</code>
   * @return The websiteKey.
   */
  java.lang.String getWebsiteKey();
  /**
   * <code>string websiteKey = 9;</code>
   * @return The bytes for websiteKey.
   */
  com.google.protobuf.ByteString
      getWebsiteKeyBytes();

  /**
   * <pre>
   * OCR
   * </pre>
   *
   * <code>string module = 10;</code>
   * @return The module.
   */
  java.lang.String getModule();
  /**
   * <pre>
   * OCR
   * </pre>
   *
   * <code>string module = 10;</code>
   * @return The bytes for module.
   */
  com.google.protobuf.ByteString
      getModuleBytes();

  /**
   * <code>bool numeric = 11;</code>
   * @return The numeric.
   */
  boolean getNumeric();

  /**
   * <code>bool case_sensitive = 12;</code>
   * @return The caseSensitive.
   */
  boolean getCaseSensitive();

  /**
   * <code>int32 minLength = 13;</code>
   * @return The minLength.
   */
  int getMinLength();

  /**
   * <code>int32 maxLength = 14;</code>
   * @return The maxLength.
   */
  int getMaxLength();

  /**
   * <pre>
   * Geetest
   * </pre>
   *
   * <code>int32 gtv = 15;</code>
   * @return The gtv.
   */
  int getGtv();

  /**
   * <code>string gt = 16;</code>
   * @return The gt.
   */
  java.lang.String getGt();
  /**
   * <code>string gt = 16;</code>
   * @return The bytes for gt.
   */
  com.google.protobuf.ByteString
      getGtBytes();

  /**
   * <code>string challenge = 17;</code>
   * @return The challenge.
   */
  java.lang.String getChallenge();
  /**
   * <code>string challenge = 17;</code>
   * @return The bytes for challenge.
   */
  com.google.protobuf.ByteString
      getChallengeBytes();

  /**
   * <code>string captchaId = 18;</code>
   * @return The captchaId.
   */
  java.lang.String getCaptchaId();
  /**
   * <code>string captchaId = 18;</code>
   * @return The bytes for captchaId.
   */
  com.google.protobuf.ByteString
      getCaptchaIdBytes();

  /**
   * <pre>
   * Common
   * </pre>
   *
   * <code>string proxy = 19;</code>
   * @return The proxy.
   */
  java.lang.String getProxy();
  /**
   * <pre>
   * Common
   * </pre>
   *
   * <code>string proxy = 19;</code>
   * @return The bytes for proxy.
   */
  com.google.protobuf.ByteString
      getProxyBytes();

  /**
   * <pre>
   * Video captcha (PopularCaptcha canvasVideo negotiation)
   * </pre>
   *
   * <code>bool canvasVideo = 20;</code>
   * @return The canvasVideo.
   */
  boolean getCanvasVideo();

  /**
   * <pre>
   * "framecount", "frameMerge", "frame", "video"
   * </pre>
   *
   * <code>string format = 21;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <pre>
   * "framecount", "frameMerge", "frame", "video"
   * </pre>
   *
   * <code>string format = 21;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <pre>
   * raw video/frame blobs (binary, no base64)
   * </pre>
   *
   * <code>repeated bytes video = 22;</code>
   * @return A list containing the video.
   */
  java.util.List<com.google.protobuf.ByteString> getVideoList();
  /**
   * <pre>
   * raw video/frame blobs (binary, no base64)
   * </pre>
   *
   * <code>repeated bytes video = 22;</code>
   * @return The count of video.
   */
  int getVideoCount();
  /**
   * <pre>
   * raw video/frame blobs (binary, no base64)
   * </pre>
   *
   * <code>repeated bytes video = 22;</code>
   * @param index The index of the element to return.
   * @return The video at the given index.
   */
  com.google.protobuf.ByteString getVideo(int index);

  /**
   * <pre>
   * frame indices from previous response
   * </pre>
   *
   * <code>repeated int32 frames = 23;</code>
   * @return A list containing the frames.
   */
  java.util.List<java.lang.Integer> getFramesList();
  /**
   * <pre>
   * frame indices from previous response
   * </pre>
   *
   * <code>repeated int32 frames = 23;</code>
   * @return The count of frames.
   */
  int getFramesCount();
  /**
   * <pre>
   * frame indices from previous response
   * </pre>
   *
   * <code>repeated int32 frames = 23;</code>
   * @param index The index of the element to return.
   * @return The frames at the given index.
   */
  int getFrames(int index);

  /**
   * <pre>
   * total frame count
   * </pre>
   *
   * <code>optional int32 framecount = 24;</code>
   * @return Whether the framecount field is set.
   */
  boolean hasFramecount();
  /**
   * <pre>
   * total frame count
   * </pre>
   *
   * <code>optional int32 framecount = 24;</code>
   * @return The framecount.
   */
  int getFramecount();

  /**
   * <pre>
   * multi-choice answers (if any)
   * </pre>
   *
   * <code>repeated string choices = 25;</code>
   * @return A list containing the choices.
   */
  java.util.List<java.lang.String>
      getChoicesList();
  /**
   * <pre>
   * multi-choice answers (if any)
   * </pre>
   *
   * <code>repeated string choices = 25;</code>
   * @return The count of choices.
   */
  int getChoicesCount();
  /**
   * <pre>
   * multi-choice answers (if any)
   * </pre>
   *
   * <code>repeated string choices = 25;</code>
   * @param index The index of the element to return.
   * @return The choices at the given index.
   */
  java.lang.String getChoices(int index);
  /**
   * <pre>
   * multi-choice answers (if any)
   * </pre>
   *
   * <code>repeated string choices = 25;</code>
   * @param index The index of the value to return.
   * @return The bytes of the choices at the given index.
   */
  com.google.protobuf.ByteString
      getChoicesBytes(int index);
}
