// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface TextSolutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.TextSolution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string texts = 1;</code>
   * @return A list containing the texts.
   */
  java.util.List<java.lang.String>
      getTextsList();
  /**
   * <code>repeated string texts = 1;</code>
   * @return The count of texts.
   */
  int getTextsCount();
  /**
   * <code>repeated string texts = 1;</code>
   * @param index The index of the element to return.
   * @return The texts at the given index.
   */
  java.lang.String getTexts(int index);
  /**
   * <code>repeated string texts = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the texts at the given index.
   */
  com.google.protobuf.ByteString
      getTextsBytes(int index);
}
