// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

/**
 * <pre>
 * VideoCanvasParams tells the client what video format to send back.
 * </pre>
 *
 * Protobuf type {@code captchasonic.v1.VideoCanvasParams}
 */
@com.google.protobuf.Generated
public final class VideoCanvasParams extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:captchasonic.v1.VideoCanvasParams)
    VideoCanvasParamsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "VideoCanvasParams");
  }
  // Use VideoCanvasParams.newBuilder() to construct.
  private VideoCanvasParams(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VideoCanvasParams() {
    format_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    frames_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_VideoCanvasParams_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_VideoCanvasParams_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_VideoCanvasParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.captchasonic.v1.VideoCanvasParams.class, com.captchasonic.v1.VideoCanvasParams.Builder.class);
  }

  private int bitField0_;
  public static final int DURATION_FIELD_NUMBER = 1;
  private int duration_ = 0;
  /**
   * <pre>
   * seconds (2 or 4)
   * </pre>
   *
   * <code>int32 duration = 1;</code>
   * @return The duration.
   */
  @java.lang.Override
  public int getDuration() {
    return duration_;
  }

  public static final int FORMAT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList format_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @return A list containing the format.
   */
  public com.google.protobuf.ProtocolStringList
      getFormatList() {
    return format_;
  }
  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @return The count of format.
   */
  public int getFormatCount() {
    return format_.size();
  }
  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @param index The index of the element to return.
   * @return The format at the given index.
   */
  public java.lang.String getFormat(int index) {
    return format_.get(index);
  }
  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the format at the given index.
   */
  public com.google.protobuf.ByteString
      getFormatBytes(int index) {
    return format_.getByteString(index);
  }

  public static final int FRAMES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList frames_ =
      emptyIntList();
  /**
   * <pre>
   * frame indices to extract (may be empty)
   * </pre>
   *
   * <code>repeated int32 frames = 3;</code>
   * @return A list containing the frames.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getFramesList() {
    return frames_;
  }
  /**
   * <pre>
   * frame indices to extract (may be empty)
   * </pre>
   *
   * <code>repeated int32 frames = 3;</code>
   * @return The count of frames.
   */
  public int getFramesCount() {
    return frames_.size();
  }
  /**
   * <pre>
   * frame indices to extract (may be empty)
   * </pre>
   *
   * <code>repeated int32 frames = 3;</code>
   * @param index The index of the element to return.
   * @return The frames at the given index.
   */
  public int getFrames(int index) {
    return frames_.getInt(index);
  }
  private int framesMemoizedSerializedSize = -1;

  public static final int FRAMECOUNT_FIELD_NUMBER = 4;
  private int framecount_ = 0;
  /**
   * <pre>
   * total frame count (null when not applicable)
   * </pre>
   *
   * <code>optional int32 framecount = 4;</code>
   * @return Whether the framecount field is set.
   */
  @java.lang.Override
  public boolean hasFramecount() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * total frame count (null when not applicable)
   * </pre>
   *
   * <code>optional int32 framecount = 4;</code>
   * @return The framecount.
   */
  @java.lang.Override
  public int getFramecount() {
    return framecount_;
  }

  public static final int VIDEO_FIELD_NUMBER = 5;
  private boolean video_ = false;
  /**
   * <pre>
   * true when full video blob needed
   * </pre>
   *
   * <code>bool video = 5;</code>
   * @return The video.
   */
  @java.lang.Override
  public boolean getVideo() {
    return video_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (duration_ != 0) {
      output.writeInt32(1, duration_);
    }
    for (int i = 0; i < format_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, format_.getRaw(i));
    }
    if (getFramesList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(framesMemoizedSerializedSize);
    }
    for (int i = 0; i < frames_.size(); i++) {
      output.writeInt32NoTag(frames_.getInt(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(4, framecount_);
    }
    if (video_ != false) {
      output.writeBool(5, video_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (duration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, duration_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < format_.size(); i++) {
        dataSize += computeStringSizeNoTag(format_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFormatList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < frames_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(frames_.getInt(i));
      }
      size += dataSize;
      if (!getFramesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      framesMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, framecount_);
    }
    if (video_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, video_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.captchasonic.v1.VideoCanvasParams)) {
      return super.equals(obj);
    }
    com.captchasonic.v1.VideoCanvasParams other = (com.captchasonic.v1.VideoCanvasParams) obj;

    if (getDuration()
        != other.getDuration()) return false;
    if (!getFormatList()
        .equals(other.getFormatList())) return false;
    if (!getFramesList()
        .equals(other.getFramesList())) return false;
    if (hasFramecount() != other.hasFramecount()) return false;
    if (hasFramecount()) {
      if (getFramecount()
          != other.getFramecount()) return false;
    }
    if (getVideo()
        != other.getVideo()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getDuration();
    if (getFormatCount() > 0) {
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormatList().hashCode();
    }
    if (getFramesCount() > 0) {
      hash = (37 * hash) + FRAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFramesList().hashCode();
    }
    if (hasFramecount()) {
      hash = (37 * hash) + FRAMECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getFramecount();
    }
    hash = (37 * hash) + VIDEO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getVideo());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.captchasonic.v1.VideoCanvasParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.captchasonic.v1.VideoCanvasParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.captchasonic.v1.VideoCanvasParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.captchasonic.v1.VideoCanvasParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * VideoCanvasParams tells the client what video format to send back.
   * </pre>
   *
   * Protobuf type {@code captchasonic.v1.VideoCanvasParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:captchasonic.v1.VideoCanvasParams)
      com.captchasonic.v1.VideoCanvasParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_VideoCanvasParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_VideoCanvasParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.captchasonic.v1.VideoCanvasParams.class, com.captchasonic.v1.VideoCanvasParams.Builder.class);
    }

    // Construct using com.captchasonic.v1.VideoCanvasParams.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      duration_ = 0;
      format_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      frames_ = emptyIntList();
      framecount_ = 0;
      video_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.captchasonic.v1.SonicProtos.internal_static_captchasonic_v1_VideoCanvasParams_descriptor;
    }

    @java.lang.Override
    public com.captchasonic.v1.VideoCanvasParams getDefaultInstanceForType() {
      return com.captchasonic.v1.VideoCanvasParams.getDefaultInstance();
    }

    @java.lang.Override
    public com.captchasonic.v1.VideoCanvasParams build() {
      com.captchasonic.v1.VideoCanvasParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.captchasonic.v1.VideoCanvasParams buildPartial() {
      com.captchasonic.v1.VideoCanvasParams result = new com.captchasonic.v1.VideoCanvasParams(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.captchasonic.v1.VideoCanvasParams result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.duration_ = duration_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        format_.makeImmutable();
        result.format_ = format_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        frames_.makeImmutable();
        result.frames_ = frames_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.framecount_ = framecount_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.video_ = video_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.captchasonic.v1.VideoCanvasParams) {
        return mergeFrom((com.captchasonic.v1.VideoCanvasParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.captchasonic.v1.VideoCanvasParams other) {
      if (other == com.captchasonic.v1.VideoCanvasParams.getDefaultInstance()) return this;
      if (other.getDuration() != 0) {
        setDuration(other.getDuration());
      }
      if (!other.format_.isEmpty()) {
        if (format_.isEmpty()) {
          format_ = other.format_;
          bitField0_ |= 0x00000002;
        } else {
          ensureFormatIsMutable();
          format_.addAll(other.format_);
        }
        onChanged();
      }
      if (!other.frames_.isEmpty()) {
        if (frames_.isEmpty()) {
          frames_ = other.frames_;
          frames_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureFramesIsMutable();
          frames_.addAll(other.frames_);
        }
        onChanged();
      }
      if (other.hasFramecount()) {
        setFramecount(other.getFramecount());
      }
      if (other.getVideo() != false) {
        setVideo(other.getVideo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              duration_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              ensureFormatIsMutable();
              format_.add(input.readStringRequireUtf8());
              break;
            } // case 18
            case 24: {
              int v = input.readInt32();
              ensureFramesIsMutable();
              frames_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureFramesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                frames_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 32: {
              framecount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              video_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int duration_ ;
    /**
     * <pre>
     * seconds (2 or 4)
     * </pre>
     *
     * <code>int32 duration = 1;</code>
     * @return The duration.
     */
    @java.lang.Override
    public int getDuration() {
      return duration_;
    }
    /**
     * <pre>
     * seconds (2 or 4)
     * </pre>
     *
     * <code>int32 duration = 1;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(int value) {

      duration_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * seconds (2 or 4)
     * </pre>
     *
     * <code>int32 duration = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000001);
      duration_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList format_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFormatIsMutable() {
      if (!format_.isModifiable()) {
        format_ = new com.google.protobuf.LazyStringArrayList(format_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @return A list containing the format.
     */
    public com.google.protobuf.ProtocolStringList
        getFormatList() {
      format_.makeImmutable();
      return format_;
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @return The count of format.
     */
    public int getFormatCount() {
      return format_.size();
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @param index The index of the element to return.
     * @return The format at the given index.
     */
    public java.lang.String getFormat(int index) {
      return format_.get(index);
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the format at the given index.
     */
    public com.google.protobuf.ByteString
        getFormatBytes(int index) {
      return format_.getByteString(index);
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @param index The index to set the value at.
     * @param value The format to set.
     * @return This builder for chaining.
     */
    public Builder setFormat(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFormatIsMutable();
      format_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @param value The format to add.
     * @return This builder for chaining.
     */
    public Builder addFormat(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFormatIsMutable();
      format_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @param values The format to add.
     * @return This builder for chaining.
     */
    public Builder addAllFormat(
        java.lang.Iterable<java.lang.String> values) {
      ensureFormatIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, format_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormat() {
      format_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ["avif","png","webm","gif"]
     * </pre>
     *
     * <code>repeated string format = 2;</code>
     * @param value The bytes of the format to add.
     * @return This builder for chaining.
     */
    public Builder addFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFormatIsMutable();
      format_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList frames_ = emptyIntList();
    private void ensureFramesIsMutable() {
      if (!frames_.isModifiable()) {
        frames_ = makeMutableCopy(frames_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * frame indices to extract (may be empty)
     * </pre>
     *
     * <code>repeated int32 frames = 3;</code>
     * @return A list containing the frames.
     */
    public java.util.List<java.lang.Integer>
        getFramesList() {
      frames_.makeImmutable();
      return frames_;
    }
    /**
     * <pre>
     * frame indices to extract (may be empty)
     * </pre>
     *
     * <code>repeated int32 frames = 3;</code>
     * @return The count of frames.
     */
    public int getFramesCount() {
      return frames_.size();
    }
    /**
     * <pre>
     * frame indices to extract (may be empty)
     * </pre>
     *
     * <code>repeated int32 frames = 3;</code>
     * @param index The index of the element to return.
     * @return The frames at the given index.
     */
    public int getFrames(int index) {
      return frames_.getInt(index);
    }
    /**
     * <pre>
     * frame indices to extract (may be empty)
     * </pre>
     *
     * <code>repeated int32 frames = 3;</code>
     * @param index The index to set the value at.
     * @param value The frames to set.
     * @return This builder for chaining.
     */
    public Builder setFrames(
        int index, int value) {

      ensureFramesIsMutable();
      frames_.setInt(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * frame indices to extract (may be empty)
     * </pre>
     *
     * <code>repeated int32 frames = 3;</code>
     * @param value The frames to add.
     * @return This builder for chaining.
     */
    public Builder addFrames(int value) {

      ensureFramesIsMutable();
      frames_.addInt(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * frame indices to extract (may be empty)
     * </pre>
     *
     * <code>repeated int32 frames = 3;</code>
     * @param values The frames to add.
     * @return This builder for chaining.
     */
    public Builder addAllFrames(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureFramesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, frames_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * frame indices to extract (may be empty)
     * </pre>
     *
     * <code>repeated int32 frames = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrames() {
      frames_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private int framecount_ ;
    /**
     * <pre>
     * total frame count (null when not applicable)
     * </pre>
     *
     * <code>optional int32 framecount = 4;</code>
     * @return Whether the framecount field is set.
     */
    @java.lang.Override
    public boolean hasFramecount() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * total frame count (null when not applicable)
     * </pre>
     *
     * <code>optional int32 framecount = 4;</code>
     * @return The framecount.
     */
    @java.lang.Override
    public int getFramecount() {
      return framecount_;
    }
    /**
     * <pre>
     * total frame count (null when not applicable)
     * </pre>
     *
     * <code>optional int32 framecount = 4;</code>
     * @param value The framecount to set.
     * @return This builder for chaining.
     */
    public Builder setFramecount(int value) {

      framecount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * total frame count (null when not applicable)
     * </pre>
     *
     * <code>optional int32 framecount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFramecount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      framecount_ = 0;
      onChanged();
      return this;
    }

    private boolean video_ ;
    /**
     * <pre>
     * true when full video blob needed
     * </pre>
     *
     * <code>bool video = 5;</code>
     * @return The video.
     */
    @java.lang.Override
    public boolean getVideo() {
      return video_;
    }
    /**
     * <pre>
     * true when full video blob needed
     * </pre>
     *
     * <code>bool video = 5;</code>
     * @param value The video to set.
     * @return This builder for chaining.
     */
    public Builder setVideo(boolean value) {

      video_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * true when full video blob needed
     * </pre>
     *
     * <code>bool video = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideo() {
      bitField0_ = (bitField0_ & ~0x00000010);
      video_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:captchasonic.v1.VideoCanvasParams)
  }

  // @@protoc_insertion_point(class_scope:captchasonic.v1.VideoCanvasParams)
  private static final com.captchasonic.v1.VideoCanvasParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.captchasonic.v1.VideoCanvasParams();
  }

  public static com.captchasonic.v1.VideoCanvasParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoCanvasParams>
      PARSER = new com.google.protobuf.AbstractParser<VideoCanvasParams>() {
    @java.lang.Override
    public VideoCanvasParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VideoCanvasParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VideoCanvasParams> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.captchasonic.v1.VideoCanvasParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

