// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: captchasonic/v1/sonic.proto
// Protobuf Java Version: 4.34.0

package com.captchasonic.v1;

@com.google.protobuf.Generated
public interface VideoCanvasParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:captchasonic.v1.VideoCanvasParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * seconds (2 or 4)
   * </pre>
   *
   * <code>int32 duration = 1;</code>
   * @return The duration.
   */
  int getDuration();

  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @return A list containing the format.
   */
  java.util.List<java.lang.String>
      getFormatList();
  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @return The count of format.
   */
  int getFormatCount();
  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @param index The index of the element to return.
   * @return The format at the given index.
   */
  java.lang.String getFormat(int index);
  /**
   * <pre>
   * ["avif","png","webm","gif"]
   * </pre>
   *
   * <code>repeated string format = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the format at the given index.
   */
  com.google.protobuf.ByteString
      getFormatBytes(int index);

  /**
   * <pre>
   * frame indices to extract (may be empty)
   * </pre>
   *
   * <code>repeated int32 frames = 3;</code>
   * @return A list containing the frames.
   */
  java.util.List<java.lang.Integer> getFramesList();
  /**
   * <pre>
   * frame indices to extract (may be empty)
   * </pre>
   *
   * <code>repeated int32 frames = 3;</code>
   * @return The count of frames.
   */
  int getFramesCount();
  /**
   * <pre>
   * frame indices to extract (may be empty)
   * </pre>
   *
   * <code>repeated int32 frames = 3;</code>
   * @param index The index of the element to return.
   * @return The frames at the given index.
   */
  int getFrames(int index);

  /**
   * <pre>
   * total frame count (null when not applicable)
   * </pre>
   *
   * <code>optional int32 framecount = 4;</code>
   * @return Whether the framecount field is set.
   */
  boolean hasFramecount();
  /**
   * <pre>
   * total frame count (null when not applicable)
   * </pre>
   *
   * <code>optional int32 framecount = 4;</code>
   * @return The framecount.
   */
  int getFramecount();

  /**
   * <pre>
   * true when full video blob needed
   * </pre>
   *
   * <code>bool video = 5;</code>
   * @return The video.
   */
  boolean getVideo();
}
